In [6]:
import pandas as pd
import numpy as np

In [4]:
data = [['ABC', 12, 3, 100],
        ['ABC', 11, 2, 50],
        ['DEF', 10, 5, 200],
        ['DEF', 9, 4, 300],
        ['GHI', 14, 3, 1000],
        ['GHI', 13, 4, 2000]
       ]

In [14]:
df= pd.DataFrame(data,columns=['A','B','C','D'])
df

     A   B  C     D
0  ABC  12  3   100
1  ABC  11  2    50
2  DEF  10  5   200
3  DEF   9  4   300
4  GHI  14  3  1000
5  GHI  13  4  2000

# syntax df.loc[row filter, column filter]

## rowfilters

In [36]:
((df['B']>10) & (df['C'] <3)).tolist()

[False, True, False, False, False, False]

In [60]:
# access individual row
df.loc[2,:]
# set of row using list
df.loc[[2,4],:]
# set of rows usning range inclusive of our range
df.loc[1:4,:]
df.loc[3:7,:]
# conditions operations ( internall reolves to a series of booleans)
condition = (df['B']>10) & (df['C'] <3)
df.loc[condition,:]
# list of booleans - list of same lenght as the rows in datafram
df.loc[[False, True, True, False, False,True],:]
# using functions collable functions returning a list or series of same size as no of rows
def fun(x):
    return x>10
df.loc[fun(df['B']).tolist(),:]

df.loc[fun(df['B']).tolist(),'A':'C']
df.loc[fun(df['B']).tolist(),['A','C','B']]
df.loc[fun(df['B']).tolist(),[True,False,True,False]]

     A  C
0  ABC  3
1  ABC  2
4  GHI  3
5  GHI  4

In [66]:
df= pd.DataFrame(data,columns=['A','B','C','D'],index=range(3,9))
df.iloc[:,:]

     A   B  C     D
3  ABC  12  3   100
4  ABC  11  2    50
5  DEF  10  5   200
6  DEF   9  4   300
7  GHI  14  3  1000
8  GHI  13  4  2000

In [68]:
df.iloc[0:3,:]

     A   B  C    D
3  ABC  12  3  100
4  ABC  11  2   50
5  DEF  10  5  200

# scoping of data

In [75]:
#condition = (df['B']>10) & (df['C'] <3)
df[['A','B']].loc[(df['B']>10) & (df['C'] <3),['A','B']]

     A   B
4  ABC  11

In [73]:
condition

3    False
4     True
5    False
6    False
7    False
8    False
dtype: bool

In [81]:
df[['A','B']] 
df.loc[(:,['A','B']]

     A   B
3  ABC  12
4  ABC  11
5  DEF  10
6  DEF   9
7  GHI  14
8  GHI  13

In [87]:
#df['E']=df['B']+10

3    22
4    21
5    20
6    19
7    24
8    23
Name: B, dtype: int64

In [89]:
df

     A   B  C     D
3  ABC  12  3   100
4  ABC  11  2    50
5  DEF  10  5   200
6  DEF   9  4   300
7  GHI  14  3  1000
8  GHI  13  4  2000

In [103]:
df.loc[df['B']%2==0,['B']] = df.loc[df['B']%2==0,['B']]+10

In [115]:
df.loc[~(df['B']%2==0),['B']] = df.loc[~(df['B']%2==0),['B']]+20

In [117]:
df

     A   B  C     D
3  ABC  22  3   100
4  ABC  31  2    50
5  DEF  20  5   200
6  DEF  29  4   300
7  GHI  24  3  1000
8  GHI  33  4  2000

In [113]:
df.loc[~(df['B']%2==0),['B']]
df.loc[(df['B']%2!=0),['B']]

    B
4  11
6   9
8  13

In [123]:
df.loc[4.5,:]=['ABC',32,20,200]

In [133]:
df.sort_index()

        A     B     C       D
3.0   ABC  22.0   3.0   100.0
4.0   ABC  31.0   2.0    50.0
4.5   ABC  32.0  20.0   200.0
5.0   DEF  20.0   5.0   200.0
6.0   DEF  29.0   4.0   300.0
7.0   GHI  24.0   3.0  1000.0
8.0   GHI  33.0   4.0  2000.0
10.0  ABC  32.0  20.0   200.0

In [137]:
df1=df.reset_index(drop=True)
df.reset_index(drop=True,inplace=True)

     A     B     C       D
0  ABC  22.0   3.0   100.0
1  ABC  31.0   2.0    50.0
2  DEF  20.0   5.0   200.0
3  DEF  29.0   4.0   300.0
4  GHI  24.0   3.0  1000.0
5  GHI  33.0   4.0  2000.0
6  ABC  32.0  20.0   200.0
7  ABC  32.0  20.0   200.0

In [145]:
df.loc[df.index.max()+1,:]=['ABCD',32,20,200]
df

         A     B     C       D
3.0    ABC  22.0   3.0   100.0
4.0    ABC  31.0   2.0    50.0
5.0    DEF  20.0   5.0   200.0
6.0    DEF  29.0   4.0   300.0
7.0    GHI  24.0   3.0  1000.0
8.0    GHI  33.0   4.0  2000.0
10.0   ABC  32.0  20.0   200.0
4.5    ABC  32.0  20.0   200.0
11.0  ABCD  32.0  20.0   200.0

In [179]:
df= pd.DataFrame(data,columns=['A','B','C','D'],index=range(3,9))
#df[['B','C','D']].abs()
#df.add_prefix("left_",axis=1)
df[['B','C','D']].agg(['min','max','sum','std','var','count','unique','nunique'])

,B,C,D
min,9,2,50
max,14,5,2000
sum,69,21,3650
std,1.870829,1.048809,764.471495
var,3.5,1.1,584416.666667
count,6,6,6
unique,"[12, 11, 10, 9, 14, 13]","[3, 2, 5, 4]","[100, 50, 200, 300, 1000, 2000]"
nunique,6,4,6

In [191]:
#[25] in [25,24,23]
df['B'].isin([9,20,14]).sum()

2

In [203]:
df['E']=df[['B','C','D']].sum(axis=1)
df

     A   B  C     D     E
3  ABC  12  3   100   115
4  ABC  11  2    50    63
5  DEF  10  5   200   215
6  DEF   9  4   300   313
7  GHI  14  3  1000  1017
8  GHI  13  4  2000  2017

In [211]:
df['B'].astype('float')

3    12.0
4    11.0
5    10.0
6     9.0
7    14.0
8    13.0
Name: B, dtype: float64

In [213]:
df['A'].str.startswith('A')

3     True
4     True
5    False
6    False
7    False
8    False
Name: A, dtype: bool

In [219]:
df=pd.DataFrame({'A':[1,2,np.nan,np.nan,3,4,np.nan,5]})
df.backfill()

C:\Users\JayanthPReddy\AppData\Local\Temp\ipykernel_2020\945815157.py:2: FutureWarning: DataFrame.backfill/Series.backfill is deprecated. Use DataFrame.bfill/Series.bfill instead
  df.backfill()

     A
0  1.0
1  2.0
2  3.0
3  3.0
4  3.0
5  4.0
6  5.0
7  5.0

In [231]:
df= pd.DataFrame(data,columns=['A','B','C','D'],index=range(3,9))
df.corr(numeric_only=True)

          B         C         D
B  1.000000 -0.356753  0.625789
C -0.356753  1.000000  0.205791
D  0.625789  0.205791  1.000000

In [241]:
#df.filter()
df

     A   B  C     D
3  ABC  12  3   100
4  ABC  11  2    50
5  DEF  10  5   200
6  DEF   9  4   300
7  GHI  14  3  1000
8  GHI  13  4  2000

In [253]:
d1={}
for index, data in df.iterrows():
    d1[index] = data.tolist()
d1

{3: ['ABC', 12, 3, 100],
 4: ['ABC', 11, 2, 50],
 5: ['DEF', 10, 5, 200],
 6: ['DEF', 9, 4, 300],
 7: ['GHI', 14, 3, 1000],
 8: ['GHI', 13, 4, 2000]}

In [263]:
x=df.set_index(['A','B'])
x
#x.reset_index()

        C     D
A   B
ABC 12  3   100
    11  2    50
DEF 10  5   200
    9   4   300
GHI 14  3  1000
    13  4  2000

In [273]:
df['B'].nlargest(4)

7    14
8    13
3    12
4    11
Name: B, dtype: int64

In [277]:
df.rank(method='dense')

     A    B    C    D
3  1.0  4.0  2.0  2.0
4  1.0  3.0  1.0  1.0
5  2.0  2.0  4.0  3.0
6  2.0  1.0  3.0  4.0
7  3.0  6.0  2.0  5.0
8  3.0  5.0  3.0  6.0

In [307]:
df = pd.DataFrame({"A":['a','b','a','a','c','b','c','c','b'],"B":[1,2,np.nan,3,np.nan,5,8,9,np.nan]})
#df.loc[(df['B'].isna()) & (df['A']=='a') ]
df

   A    B
0  a  1.0
1  b  2.0
2  a  NaN
3  a  3.0
4  c  NaN
5  b  5.0
6  c  8.0
7  c  9.0
8  b  NaN

In [305]:
df.loc[(df['A']=='a'),['B']].mean()

B    2.0
dtype: float64

In [365]:
df = pd.DataFrame({"A":['a','b','a','a','c','b','c','c','b'],"B":[1,2,np.nan,3,np.nan,5,8,9,np.nan]})
df.loc[(df['B'].isna()) & (df['A']=='a'),['B'] ] = df.loc[(df['A']=='a'),['B']].mean().values[0]
df.loc[(df['B'].isna()) & (df['A']=='b'), ['B']] = df.loc[(df['A']=='b'),['B']].mean().values[0]
df.loc[(df['B'].isna()) & (df['A']=='c'),['B'] ] = df.loc[(df['A']=='c'),['B']].mean().values[0]
df

   A    B
0  a  1.0
1  b  2.0
2  a  2.0
3  a  3.0
4  c  8.5
5  b  5.0
6  c  8.0
7  c  9.0
8  b  3.5

In [381]:
df = pd.DataFrame({"A":['a','b','a','a','c','b','c','c','b'],"B":[1,2,np.nan,3,np.nan,5,8,9,np.nan]})
for i in df['A'].unique().tolist():
    #df.loc[(df['B'].isna()) & (df['A']==i),['B'] ] = df.loc[(df['A']==i),['B']].mean().values[0]
    df.loc[(df['B'].isna()) & (df['A']==i),['B'] ] = df.groupby('A')['B'].mean()[i]
df

   A    B
0  a  1.0
1  b  2.0
2  a  2.0
3  a  3.0
4  c  8.5
5  b  5.0
6  c  8.0
7  c  9.0
8  b  3.5

In [393]:
df = pd.DataFrame({"A":['a','b','a','a','c','b','c','c','b'],"B":[1,2,np.nan,3,np.nan,5,8,9,np.nan]})

# apply

In [416]:
df = pd.DataFrame({"A":['a','b','a','a','c','b','c','c','b'],"B":[1,2,np.nan,3,np.nan,5,8,9,np.nan]})
def fun(x):
    if (x.dtypes == 'object'):
        return "".join(x.tolist())
    else:
        return x.sum()
df.apply(fun,axis=0)

A    abaacbccb
B         28.0
dtype: object

In [456]:
df = pd.DataFrame({"A":['a','b','a','a','c','b','c','c','b'],"B":[1,2,np.nan,3,np.nan,5,8,9,np.nan]})
def fun(x):
    #print(x.name,x['A'],x['B'])
    return x['B']+100 
df.apply(fun,axis=1)
df

   A    B
0  a  1.0
1  b  2.0
2  a  NaN
3  a  3.0
4  c  NaN
5  b  5.0
6  c  8.0
7  c  9.0
8  b  NaN

In [464]:
df = pd.DataFrame({"A":['a','b','a','a','c','b','c','c','b'],"B":[1,2,np.nan,3,np.nan,5,8,9,np.nan]})
def fun(x):
    x['C'] = x['B']+100
    return x
df.apply(fun,axis=1)

   A    B      C
0  a  1.0  101.0
1  b  2.0  102.0
2  a  NaN    NaN
3  a  3.0  103.0
4  c  NaN    NaN
5  b  5.0  105.0
6  c  8.0  108.0
7  c  9.0  109.0
8  b  NaN    NaN

In [448]:
df = pd.DataFrame({"A":['a','b','a','a','c','b','c','c','b'],"B":[1,2,np.nan,3,np.nan,5,8,9,np.nan]})
def fun(x):
    print(x.mean())
df.groupby('A').apply(fun)

B    2.0
dtype: float64
B    3.5
dtype: float64
B    8.5
dtype: float64

Empty DataFrame
Columns: []
Index: []

In [466]:
df = pd.DataFrame({"A":['a','b','a','a','c','b','c','c','b'],"B":[1,2,np.nan,3,np.nan,5,8,9,np.nan]})
def fun(x,y):
    print(x,y)
df.groupby('A').apply(fun,10)

   A    B
0  a  1.0
2  a  NaN
3  a  3.0 10
   A    B
1  b  2.0
5  b  5.0
8  b  NaN 10
   A    B
4  c  NaN
6  c  8.0
7  c  9.0 10

C:\Users\JayanthPReddy\AppData\Local\Temp\ipykernel_2020\1820309230.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('A').apply(fun,10)

Empty DataFrame
Columns: []
Index: []