In [179]:
import pandas as pd
from datetime import datetime
import warnings
# Suppress all warnings
warnings.filterwarnings("ignore")

## Series.dt Accessor 
- The .dt accessor in pandas is a convenient way to access datetime-like properties of a pandas Series object.
- The .dt accessor allows you to extract various components of a datetime, such as the year, month, day, hour, minute, second, and many more.

#### Note: It is specifically designed for Series with datetime values (i.e., datetime64 type).

### Mentioned Below are the Date time related properties of pandas series.dt accessor
- Series.dt.date: Returns the date part of the datetime without the time.
- Series.dt.time: Returns the time part of the datetime without the date.
- Series.dt.timetz: Returns the time part of the datetime with the time zone information.
- Series.dt.year: The year of each datetime.
- Series.dt.month: The month of each datetime (1 = January, 12 = December).
- Series.dt.day: The day of the month for each datetime.
- Series.dt.hour: The hour of each datetime.
- Series.dt.minute: The minute of each datetime.
- Series.dt.second: The second of each datetime.
- Series.dt.microsecond: The microsecond of each datetime.
- Series.dt.nanosecond: The nanosecond of each datetime.
- Series.dt.dayofweek: The day of the week with Monday=0, Sunday=6.
- Series.dt.weekday: Alias for dayofweek.
- Series.dt.day_name(): Returns the name of the day of the week.
- Series.dt.week: The week ordinal of the year.
- Series.dt.weekofyear: Alias for week (deprecated).
- Series.dt.dayofyear: The ordinal day of the year.
- Series.dt.quarter: The quarter of the date.
- Series.dt.is_month_start: Indicates if the date is the first day of the month.
- Series.dt.is_month_end: Indicates if the date is the last day of the month.
- Series.dt.is_quarter_start: Indicates if the date is the first day of the quarter.
- Series.dt.is_quarter_end: Indicates if the date is the last day of the quarter.
- Series.dt.is_year_start: Indicates if the date is the first day of the year.
- Series.dt.is_year_end: Indicates if the date is the last day of the year.
- Series.dt.is_leap_year: Indicates if the date belongs to a leap year.
- Series.dt.days_in_month or Series.dt.daysinmonth: The number of days in the month.
- Series.dt.tz: The time zone of the datetime.
- Series.dt.freq: The frequency object if it is set, otherwise None.

Use the below hyperlink for more information on series.dt accessories

https://www.slingacademy.com/article/using-pandas-series-dt-accessor-to-work-with-date-and-time/

In [210]:
# Creating a date range with daily frequency
date_range = pd.date_range(start='2023-01-01', end='2023-01-10', freq='D')
series = pd.Series(date_range)

some of the properties are mention with example

#### dt.is_leap_year property

In [215]:
print(series.dt.is_leap_year)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

#### dt.freq property

In [216]:
print(series.dt.freq)

D

# String to Date Time Conversion

### pandas.to_datetime() syntax:
#### pandas.to_datetime(arg, errors=’raise’, dayfirst=False, yearfirst=False, utc=None, box=True, format=None, exact=True, unit=None, infer_datetime_format=False, origin=’unix’, cache=False)
#### Parameters:
- arg: An integer, string, float, list or dict object to convert in to Date time object.
- dayfirst: Boolean value, places day first if True.
- yearfirst: Boolean value, places year first if True.
- utc: Boolean value, Returns time in UTC if True.
- format: String input to tell position of day, month and year.
- Return type: Datetimeme

#### Note:
The default date format, when none is specified, is typically Month-Day-Year (i.e., mm/dd/yyyy).It handles most of the cases even though it is not mentioned in the correct format

To determine whether a given date is valid:
1) Identify the Year:

  - If there is a four-digit value, it is considered the year.
  - If there isn't a four-digit value, select the value that cannot be valid for both the month and the day (i.e., a value greater than 12   is not a valid month).
2) Identify the Month and Day:
  - Of the remaining two values, one should be less than or equal to 12 (indicating it can be a valid month).
  - The other value should be in the correct range for that month and year (indicating a valid day).

In [8]:
df=pd.DataFrame({'date1':['2022-05-04','2023-06-05','2024-07-06'],#YYYY-MM-DD
                 'date2':['05/04/2022','06/05/2023','07/06/2024'],#MM/DD/YYYY
                 'date3':['05/04/22','06/05/23','07/06/24'],#DD/MM/YY
                 'date4':['04-May-2022','05-June-2023','06-July-2024'],#Day-Month-Year
                 'date5':['May/04/22','Jun/05/23','Jul/06/24'],#Mon/DD/YY
#                'datetime':['2022-05-04T14:30:00','2023-06-05T15:30:00','2024-07-06T16:30:00'],#YYYY-MM-DDTHH:MM:SS
                 'datetime':['2022-05-04 14:30:00','2023-06-05 15:30:00','2024-07-06 16:30:00'],#YYYY-MM-DD HH:MM:SS
                 })
df

,date1,date2,date3,date4,date5,datetime
0,2022-05-04,05/04/2022,05/04/22,04-May-2022,May/04/22,2022-05-04 14:30:00
1,2023-06-05,06/05/2023,06/05/23,05-June-2023,Jun/05/23,2023-06-05 15:30:00
2,2024-07-06,07/06/2024,07/06/24,06-July-2024,Jul/06/24,2024-07-06 16:30:00

#### formats of the date columns
- 1) date1 - YYYY-MM-DD
  2) date2 - MM/DD/YYYY
  3) date3 - DD/MM/YY
  4) date4 - Day-Month-Year
  5) date5 - Mon/DD/YY
  6) datetime - YYYY-MM-DD HH:MM:SS

### Default String conversion to Datetime without any arguments

Default string conversion to Date time without any arguments is illustrated below and irrespective of the format of string, the date of parsed format will always be converted to "YYYY-MM-DD" format

#### Orignial Data Frame

In [189]:
df=pd.DataFrame({'date1':['2022-05-04','2023-06-05','2024-07-06'],#YYYY-MM-DD
                 'date2':['05/04/2022','06/05/2023','07/06/2024'],#MM/DD/YYYY
                 'date3':['05/04/22','06/05/23','07/06/24'],#DD/MM/YY
                 'date4':['04-May-2022','05-June-2023','06-July-2024'],#Day-Month-Year
                 'date5':['May/04/22','Jun/05/23','Jul/06/24'],#Mon/DD/YY
                 'datetime':['2022-05-04 14:30:00','2023-06-05 15:30:00','2024-07-06 16:30:00'],#YYYY-MM-DD HH:MM:SS
                 })
df

,date1,date2,date3,date4,date5,datetime
0,2022-05-04,05/04/2022,05/04/22,04-May-2022,May/04/22,2022-05-04 14:30:00
1,2023-06-05,06/05/2023,06/05/23,05-June-2023,Jun/05/23,2023-06-05 15:30:00
2,2024-07-06,07/06/2024,07/06/24,06-July-2024,Jul/06/24,2024-07-06 16:30:00

#### Dataframe After Conversion

In [7]:
df.apply(pd.to_datetime)

       date1      date2      date3      date4      date5            datetime
0 2022-05-04 2022-05-04 2022-05-04 2022-05-04 2022-05-04 2022-05-04 14:30:00
1 2023-06-05 2023-06-05 2023-06-05 2023-06-05 2023-06-05 2023-06-05 15:30:00
2 2024-07-06 2024-07-06 2024-07-06 2024-07-06 2024-07-06 2024-07-06 16:30:00

### String conversion to Datetime with dayfirst argument

Dayfirst Argument is used to avoid the ambiguity between DD/MM/YYYY and MM/DD/YYYY and should be used as follows:
* If your date format is DD/MM/YYYY, set dayfirst=True.
* If your date format is MM/DD/YYYY, set dayfirst=False.
  
#### Note:
Since Pandas tries to infer the format of the date based on the data provided, but it generally assumes the MM/DD/YYYY format when there is ambiguity between DD/MM/YYYY and MM/DD/YYYY. This is particularly true if the day value is less than or equal to 12, as it could be interpreted as a month.
- To avoid ambiguity and ensure the correct format is used, you should specify the dayfirst parameter

#### Orignial Data Frame

In [187]:
df=pd.DataFrame({'date1':['2022-05-04','2023-06-05','2024-07-06'],#YYYY-MM-DD
                 'date2':['05/04/2022','06/05/2023','07/06/2024'],#MM/DD/YYYY
                 'date3':['05/04/22','06/05/23','07/06/24'],#DD/MM/YY
                 'date4':['04-May-2022','05-June-2023','06-July-2024'],#Day-Month-Year
                 'date5':['May/04/22','Jun/05/23','Jul/06/24'],#Mon/DD/YY
                 'datetime':['2022-05-04 14:30:00','2023-06-05 15:30:00','2024-07-06 16:30:00'],#YYYY-MM-DD HH:MM:SS
                 })
df

,date1,date2,date3,date4,date5,datetime
0,2022-05-04,05/04/2022,05/04/22,04-May-2022,May/06/22,2022-05-04T14:30:00
1,2023-06-05,06/05/2023,06/05/23,05-June-2023,Jun/05/23,2023-06-05T15:30:00
2,2024-07-06,07/06/2024,07/06/24,06-July-2024,Jul/06/24,2024-07-06T16:30:00

#### Dataframe After Conversion

In [188]:
df.apply(pd.to_datetime,dayfirst=True)

       date1      date2      date3      date4      date5            datetime
0 2022-04-05 2022-04-05 2022-04-05 2022-05-04 2022-05-06 2022-04-05 14:30:00
1 2023-05-06 2023-05-06 2023-05-06 2023-06-05 2023-06-05 2023-05-06 15:30:00
2 2024-06-07 2024-06-07 2024-06-07 2024-07-06 2024-07-06 2024-06-07 16:30:00

#### another way of writing it

In [7]:
def conv_to_datetime(x):
    return(pd.to_datetime(x,dayfirst=True))

In [8]:
df.apply(conv_to_datetime)

       date1      date2      date3      date4      date5            datetime
0 2022-04-05 2022-04-05 2022-04-05 2022-05-04 2022-05-04 2022-04-05 14:30:00
1 2023-05-06 2023-05-06 2023-05-06 2023-06-05 2023-06-05 2023-05-06 15:30:00
2 2024-06-07 2024-06-07 2024-06-07 2024-07-06 2024-07-06 2024-06-07 16:30:00

### String conversion to Datetime with yearfirst argument

- Yearfirst should be set true if the string to be parsed is in formats where year is the first element like 'YY/MM/DD' 
- Note : if the year is in 'YYYY/MM/DD' format then the first element is directly considered as year even when yearfirst is False

#### Orignial Data Frame

In [9]:
df=pd.DataFrame({'date1':['2022-05-04','2023-06-05','2024-07-06'],#YYYY-MM-DD
                 'date2':['05/04/2022','06/05/2023','07/06/2024'],#MM/DD/YYYY
                 'date3':['05/04/22','06/05/23','07/06/24'],#DD/MM/YY
                 'date4':['04-May-2022','05-June-2023','06-July-2024'],#Day-Month-Year
                 'date5':['May/04/22','Jun/05/23','Jul/06/24'],#Mon/DD/YY
                 'datetime':['2022-05-04 14:30:00','2023-06-05 15:30:00','2024-07-06 16:30:00'],#YYYY-MM-DD HH:MM:SS
                 })
df

,date1,date2,date3,date4,date5,datetime
0,2022-05-04,05/04/2022,05/04/22,04-May-2022,May/04/22,2022-05-04T14:30:00
1,2023-06-05,06/05/2023,06/05/23,05-June-2023,Jun/05/23,2023-06-05T15:30:00
2,2024-07-06,07/06/2024,07/06/24,06-July-2024,Jul/06/24,2024-07-06T16:30:00

#### Dataframe After Conversion

In [10]:
df.apply(pd.to_datetime,yearfirst=True)

       date1      date2      date3      date4      date5            datetime
0 2022-05-04 2022-05-04 2005-04-22 2022-05-04 2022-05-04 2022-05-04 14:30:00
1 2023-06-05 2023-06-05 2006-05-23 2023-06-05 2023-06-05 2023-06-05 15:30:00
2 2024-07-06 2024-07-06 2007-06-24 2024-07-06 2024-07-06 2024-07-06 16:30:00

### String conversion to Datetime with dayfirst,yearfirst argument

When both dayfirst and yearfirst are used:
* yearfirst takes precedence in identifying the year.
* dayfirst helps in distinguishing between DD/MM and MM/DD for date strings where yearfirst does not apply.

It's generally a good idea to use only one of these arguments (dayfirst or yearfirst) at a time to avoid confusion unless you have a specific case where both are necessary to handle a complex date format.

#### Orignial Data Frame

In [11]:
df=pd.DataFrame({'date1':['2022-05-04','2023-06-05','2024-07-06'],#YYYY-MM-DD
                 'date2':['05/04/2022','06/05/2023','07/06/2024'],#MM/DD/YYYY
                 'date3':['05/04/22','06/05/23','07/06/24'],#DD/MM/YY
                 'date4':['04-May-2022','05-June-2023','06-July-2024'],#Day-Month-Year
                 'date5':['May/04/22','Jun/05/23','Jul/06/24'],#Mon/DD/YY
                 'datetime':['2022-05-04 14:30:00','2023-06-05 15:30:00','2024-07-06 16:30:00'],#YYYY-MM-DD HH:MM:SS
                 })
df

,date1,date2,date3,date4,date5,datetime
0,2022-05-04,05/04/2022,05/04/22,04-May-2022,May/04/22,2022-05-04T14:30:00
1,2023-06-05,06/05/2023,06/05/23,05-June-2023,Jun/05/23,2023-06-05T15:30:00
2,2024-07-06,07/06/2024,07/06/24,06-July-2024,Jul/06/24,2024-07-06T16:30:00

#### Dataframe After Conversion

In [12]:
df.apply(pd.to_datetime,dayfirst=True,yearfirst=True)

       date1      date2      date3      date4      date5            datetime
0 2022-04-05 2022-04-05 2005-04-22 2022-05-04 2022-05-04 2022-04-05 14:30:00
1 2023-05-06 2023-05-06 2006-05-23 2023-06-05 2023-06-05 2023-05-06 15:30:00
2 2024-06-07 2024-06-07 2007-06-24 2024-07-06 2024-07-06 2024-06-07 16:30:00

### String conversion to Datetime with utc argument

 The utc parameter specifies whether or not to convert the resulting datetime object to Coordinated Universal Time (UTC).

When you use utc=True in pd.to_datetime(), it will:

Convert the date or time to a timezone-aware datetime object in UTC.
- If the input is already timezone-aware, it will convert the input to UTC.
- If the input is naive (i.e., does not have timezone information), it will assume it is in the local timezone and then convert it to UTC.

#### Orignial Data Frame

In [190]:
df=pd.DataFrame({'date1':['2022-05-04','2023-06-05','2024-07-06'],#YYYY-MM-DD
                 'date2':['05/04/2022','06/05/2023','07/06/2024'],#MM/DD/YYYY
                 'date3':['05/04/22','06/05/23','07/06/24'],#DD/MM/YY
                 'date4':['04-May-2022','05-June-2023','06-July-2024'],#Day-Month-Year
                 'date5':['May/04/22','Jun/05/23','Jul/06/24'],#Mon/DD/YY
                 'datetime':['2022-05-04 14:30:00','2023-06-05 15:30:00','2024-07-06 16:30:00'],#YYYY-MM-DD HH:MM:SS
                 })
df

,date1,date2,date3,date4,date5,datetime
0,2022-05-04,05/04/2022,05/04/22,04-May-2022,May/04/22,2022-05-04 14:30:00
1,2023-06-05,06/05/2023,06/05/23,05-June-2023,Jun/05/23,2023-06-05 15:30:00
2,2024-07-06,07/06/2024,07/06/24,06-July-2024,Jul/06/24,2024-07-06 16:30:00

#### Dataframe After Conversion

In [55]:
df.apply(pd.to_datetime,utc=True)

,date1,date2,date3,date4,date5,datetime
0,2022-05-04 00:00:00+00:00,2022-05-04 00:00:00+00:00,2022-05-04 00:00:00+00:00,2022-05-04 00:00:00+00:00,2005-05-04 00:00:00+00:00,2022-05-04 14:30:00+00:00
1,2023-06-05 00:00:00+00:00,2023-06-05 00:00:00+00:00,2023-06-05 00:00:00+00:00,2023-06-05 00:00:00+00:00,2023-06-05 00:00:00+00:00,2023-06-05 15:30:00+00:00
2,2024-07-06 00:00:00+00:00,2024-07-06 00:00:00+00:00,2024-07-06 00:00:00+00:00,2024-07-06 00:00:00+00:00,2024-07-06 00:00:00+00:00,2024-07-06 16:30:00+00:00

### String conversion to Datetime with Format argument

- Format argument is used to specify the exact format of the date and time strings that you want to convert into datetime objects.
- This is particularly useful when the input date strings have a consistent format that is not easily recognized or is ambiguous to the automatic parsing algorithm of pandas.

#### Orignial Data Frame

In [192]:
df=pd.DataFrame({'date1':['2022-05-04','2023-06-05','2024-07-06'],#YYYY-MM-DD
                 'date2':['05/04/2022','06/05/2023','07/06/2024'],#MM/DD/YYYY
                 'date3':['05/04/22','06/05/23','07/06/24'],#DD/MM/YY
                 'date4':['04-May-2022','05-June-2023','06-July-2024'],#Day-Month-Year
                 'date5':['May/04/22','Jun/05/23','Jul/06/24'],#Mon/DD/YY
                 'datetime':['2022-05-04 14:30:00','2023-06-05 15:30:00','2024-07-06 16:30:00'],#YYYY-MM-DD HH:MM:SS
                 })
df

,date1,date2,date3,date4,date5,datetime
0,2022-05-04,05/04/2022,05/04/22,04-May-2022,May/04/22,2022-05-04 14:30:00
1,2023-06-05,06/05/2023,06/05/23,05-June-2023,Jun/05/23,2023-06-05 15:30:00
2,2024-07-06,07/06/2024,07/06/24,06-July-2024,Jul/06/24,2024-07-06 16:30:00

In [16]:
pd.to_datetime(df['date2'],format='%d/%m/%Y')

0   2022-04-05
1   2023-05-06
2   2024-06-07
Name: date2, dtype: datetime64[ns]

In [17]:
pd.to_datetime(df['date3'],format='%y/%m/%d')

0   2005-04-22
1   2006-05-23
2   2007-06-24
Name: date3, dtype: datetime64[ns]

In [19]:
pd.to_datetime(df['date4'],format='%d-%B-%Y')

0   2022-05-04
1   2023-06-05
2   2024-07-06
Name: date4, dtype: datetime64[ns]

In [20]:
pd.to_datetime(df['datetime'],format='%Y-%m-%dT%H:%M:%S')

0   2022-05-04 14:30:00
1   2023-06-05 15:30:00
2   2024-07-06 16:30:00
Name: datetime, dtype: datetime64[ns]

### String conversion to Datetime with Format along with exact argument

- When using format with exact=False, pandas may still parse the dates and ignore extra time information or other deviations, as long as the date portion matches the specified format.
- When using format with exact=True, any deviation from the exact format will result in a ValueError.
  
Example to understand the exact use case of this function is shown below

In [201]:
dates_with_time = ['2024-09-05 12:00:00', '2024-09-06 12:00:00', '2024-09-07 12:00:00']

#### without exact=False

In [202]:
try:
    pd.to_datetime(dates_with_time, format='%Y-%m-%d',exact=False)
    print("Dates were parsed successfully.")
    print(pd.to_datetime(dates_with_time, format='%Y-%m-%d',exact=False))
except ValueError as e:
    print(f"Error: {e}")

Dates were parsed successfully.
DatetimeIndex(['2024-09-05', '2024-09-06', '2024-09-07'], dtype='datetime64[ns]', freq=None)

#### without exact=True

In [203]:
# Using format with exact=True
try:
    pd.to_datetime(dates_with_time, format='%Y-%m-%d',exact=True)
    print("Dates were parsed successfully.")
except ValueError as e:
    print(f"Error: {e}")

Error: unconverted data remains when parsing with format "%Y-%m-%d": " 12:00:00", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

## datetime.strptime() Method

- datetime.strptime() is a method in Python's datetime module that allows you to parse a date string into a datetime object based on a specific format.
- It is very similar to pd.to_datetime() with the format argument in pandas, but datetime.strptime() is part of the standard library and works specifically with individual date strings rather than series or DataFrames.

## On Individual String

In [194]:
from datetime import datetime
import datetime as dt
# date string in DD-MM-YYYY format
date_str = '05-01-2024'
datestr1='2022-05-04 14:30:00'

In [195]:
# Convert to datetime object using strptime()
print('Format Allowed :"DD-MM-YYYY"')
print(datetime.strptime(date_str, '%d-%m-%Y'))

Format Allowed :"DD-MM-YYYY"
2024-01-05 00:00:00

In [197]:
print('Format Allowed :"YYYY-MM-DD hh:mm:ss"')
print(datetime.strptime(datestr1,'%Y-%m-%d %H:%M:%S'))

Format Allowed :"YYYY-MM-DD hh:mm:ss"
2022-05-04 14:30:00

### On Pandas Data Frame

#### Orignial Data Frame

In [198]:
df

,date1,date2,date3,date4,date5,datetime
0,2022-05-04,05/04/2022,05/04/22,04-May-2022,May/04/22,2022-05-04 14:30:00
1,2023-06-05,06/05/2023,06/05/23,05-June-2023,Jun/05/23,2023-06-05 15:30:00
2,2024-07-06,07/06/2024,07/06/24,06-July-2024,Jul/06/24,2024-07-06 16:30:00

In [199]:
def Parse_date_Format(date_string):
    return datetime.strptime(date_string, "%Y-%m-%d %H:%M:%S")

In [200]:
df['datetime'].apply(Parse_date_Format)

0   2022-05-04 14:30:00
1   2023-06-05 15:30:00
2   2024-07-06 16:30:00
Name: datetime, dtype: datetime64[ns]

# Date time to String Conversion

strftime is a method in Python used to format datetime objects into readable strings. It allows you to specify the format in which you want to display the date and time.
- format: A string representing the desired format for the datetime object. The format codes are based on Python's strftime directives, such as %Y for the full year, %m for the month, %d for the day, etc.

Refer to the below hyperlink to get information about the format codes for all the Date and Time related properties

https://docs.python.org/3/library/datetime.html#format-codes

## On Individual String

### datetime.strftime() Method

In [30]:
date_string = "2023-12-25 15:30:00"
date_object = datetime.strptime(date_string, "%Y-%m-%d %H:%M:%S")

In [31]:
print("Input Format : YYY-MM-DD hh:mm:ss")
print("To Format - Day, DD Month YYYY :",date_object.strftime("%A, %d %B %Y"))
print("To Format - DD/MM/YY hh:mm",date_object.strftime("%d/%m/%Y %I:%M %p"))

Input Format : YYY-MM-DD hh:mm:ss
To Format - Day, DD Month YYYY : Monday, 25 December 2023
To Format - DD/MM/YY hh:mm 25/12/2023 03:30 PM

## On Pandas series

### datetime.strftime() Method

#### Orignial Data Frame

In [65]:
df

,date1,date2,date3,date4,date5,datetime
0,2022-05-04,05/04/2022,05/04/22,04-May-2022,May/04/05,2022-05-04T14:30:00
1,2023-06-05,06/05/2023,06/05/23,05-June-2023,Jun/05/23,2023-06-05T15:30:00
2,2024-07-06,07/06/2024,07/06/24,06-July-2024,Jul/06/24,2024-07-06T16:30:00

In [33]:
def Format_date(date_string):
    # Convert the string to a datetime object
    date_object = datetime.strptime(date_string, "%Y-%m-%dT%H:%M:%S")
    # Format the datetime object into a new string format
    return date_object.strftime("%A, %d %B %Y at %I:%M %p")

In [34]:
df['datetime'].apply(Format_date)

0    Wednesday, 04 May 2022 at 02:30 PM
1      Monday, 05 June 2023 at 03:30 PM
2    Saturday, 06 July 2024 at 04:30 PM
Name: datetime, dtype: object

### using series.dt.strftime

Series.dt.strftime() is a method to convert the datetime values in a pandas Series to a string format according to the provided format string.
Parameters
- format: A string representing the desired format for the datetime object. The format codes are based on Python's strftime directives, such as %Y for the full year, %m for the month, %d for the day, etc.

Refer to the below hyperlink to get information about the format codes for all the Date and Time related properties

https://docs.python.org/3/library/datetime.html#format-codes

Note : 
- If the input is pandas Series with only date information and if the function pd.to_datetime() is used on it directly, pandas will take     default time value 00:00:00
- If the input is pandas Series with only time information and if the function pd.to_datetime() is used on it directly, pandas will add the current date to the datetime object.

In [185]:
series=pd.Series(['04-05-2024 08:45:00','06-02-2025 09:30:00'])
#series=pd.Series(['04-05-2024 ','06-02-2025 '])
#series=pd.Series(['08:45:00','09:30:00'])
print('Considering The below series with Timestamp values:')
dt_series=pd.to_datetime(series)
print(dt_series)
print("Output Format: YYY-MM-DD hh:mm:ss")
dt_series.dt.strftime("%d/%m/%Y %I:%M %p")

Considering The below series with Timestamp values:
0   2024-04-05 08:45:00
1   2025-06-02 09:30:00
dtype: datetime64[ns]
Output Format: YYY-MM-DD hh:mm:ss

0    05/04/2024 08:45 AM
1    02/06/2025 09:30 AM
dtype: object