In [13]:
def fun(x,**kwargs):
    print(x,kwargs['l'],kwargs['y'],kwargs.keys())
fun(l=20,y=30,x=10)

10 20 30 dict_keys(['l', 'y'])

In [15]:
x= ['abc','defg','c','rt']
sorted(x,key=len)

['c', 'rt', 'abc', 'defg']

In [17]:
data = [['ABC', 12, 3, 100],
        ['ABC', 11, 2, 50],
        ['DEF', 10, 5, 200],
        ['DEF', 9, 4, 300],
        ['GHI', 14, 3, 1000],
        ['GHI', 13, 4, 2000]
       ]
sorted(data,key=lambda x:x[1])

[['DEF', 9, 4, 300],
 ['DEF', 10, 5, 200],
 ['ABC', 11, 2, 50],
 ['ABC', 12, 3, 100],
 ['GHI', 13, 4, 2000],
 ['GHI', 14, 3, 1000]]

In [21]:
data = [['ABC', 12, 3, 100],
        ['ABC', 11, 2, 50],
        ['DEF', 10, 5, 200],
        ['DEF', 9, 4, 300],
        ['GHI', 14, 3, 1000],
        ['GHI', 13, 4, 2000]
       ]
sorted(data,key=lambda x:(x[2],-x[1]))

[['ABC', 11, 2, 50],
 ['GHI', 14, 3, 1000],
 ['ABC', 12, 3, 100],
 ['GHI', 13, 4, 2000],
 ['DEF', 9, 4, 300],
 ['DEF', 10, 5, 200]]

In [25]:
# map(func, iterable) applies function on each element of the iterable
import math
list(map(math.sqrt,[1,4,9,16]))

[1.0, 2.0, 3.0, 4.0]

In [31]:
def fun(x,y):
    return(x+y)
list(map(fun,[1,2,3],[4,5,6])),list(map(fun,[1,2],[4,5,6]))

([5, 7, 9], [5, 7])

In [53]:
from functools import reduce

#reduce(func, iterable, intial(o))
def fun(x,y):
    return min(x,y)
reduce(fun,[1,2,3,4,5],-1)

-1

In [65]:
def fun(x,y):
    return x+y
def average(l):
    return reduce(fun,l)/len(l)
average([1,2,3,4,5])

3.0

In [75]:
l= [1,2,3,4,5]
def fun(l):
    l[1]=100
    print(l)
print(l)
fun(l[:])
print(l)

[1, 2, 3, 4, 5]
[1, 100, 3, 4, 5]
[1, 2, 3, 4, 5]

[1,2,3,4,5]
[1100,3,4,5]
[1,100,3,4,5]

In [79]:
l= [1,2,[3,7,8],4,5]
def fun(l):
    l[2][1]=100
    print(l)
print(l)
fun(l[:])
print(l)

[1, 2, [3, 7, 8], 4, 5]
[1, 2, [3, 100, 8], 4, 5]
[1, 2, [3, 100, 8], 4, 5]

In [81]:
from copy import deepcopy
l= [1,2,[3,7,8],4,5]
def fun(l):
    l[2][1]=100
    print(l)
print(l)
fun(deepcopy(l))
print(l)

[1, 2, [3, 7, 8], 4, 5]
[1, 2, [3, 100, 8], 4, 5]
[1, 2, [3, 7, 8], 4, 5]

[1,2,[3,7,8],4,5]
[1,2,[3,100,8],4,5]
[1,2,[3,7,8],4,5]

# Assignment - generate fibanocci series using reduce function

# Pandas

Series( single column data frames, notion of axis doent exisit), Dataframe(Multicolumn,notion of of axis exists)
mutable

## Create
### From list, dict, series, import from diff data formats ( excel, csv, json, parquet.........)

In [154]:
import pandas as pd
lst =[[1,2,3],[4,5,6],[7,8,9]]
pd.DataFrame(lst)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [160]:
dict1 ={'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]}
pd.DataFrame(dict1)

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [176]:
series1 = pd.Series([1,2,3])
series2 = pd.Series([3,4])
dict1 ={'A':series1,'B':series2}
df=pd.DataFrame(dict1)
df

   A    B
0  1  3.0
1  2  4.0
2  3  NaN

In [214]:
x=pd.DataFrame()
x['A'] = df['A']
x['B'] = df['B']
x

   A    B
0  1  3.0
1  2  4.0
2  3  NaN

# experiement with each argument , how it works

In [ ]:
pd.read_csv()

In [108]:
pd.DataFrame(lst, columns=['A','B','C'], index =['a','b','c'])

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [110]:
lst =[[1,2,3],[4,5,6],[7,8,9]]
df=pd.DataFrame(lst)
df.columns = ['A','B','C']
df.index = ['a','b','c']
df.dtypes

A    int64
B    int64
C    int64
dtype: object

In [126]:
df.shape,df.ndim,df.dtypes,df.all(axis=0),df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

((3, 3),
 2,
 A    int64
 B    int64
 C    int64
 dtype: object,
 A    False
 B     True
 C     True
 dtype: bool,
 None)

In [124]:
lst =[[1,2,3],[0,5,6],[7,8,9]]
df=pd.DataFrame(lst)
df.columns = ['A','B','C']
df.index = ['a','b','c']
df.all(axis=0)

A    False
B     True
C     True
dtype: bool

In [132]:
lst =[[pd.NA,2,3],[pd.NA,5,6],[7,pd.NA,9]]
df=pd.DataFrame(lst)
df.columns = ['A','B','C']
df.index = ['a','b','c']
df,df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       1 non-null      object
 1   B       2 non-null      object
 2   C       3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes

(      A     B  C
 a  <NA>     2  3
 b  <NA>     5  6
 c     7  <NA>  9,
 None)

In [140]:
df.isnull().sum(),df.isnull().sum(axis=1)

(A    2
 B    1
 C    0
 dtype: int64,
 a    1
 b    1
 c    1
 dtype: int64)

In [152]:
x=df.isnull()
x.sum(),x.sum(axis=1),df.sum()

(A    2
 B    1
 C    0
 dtype: int64,
 a    1
 b    1
 c    1
 dtype: int64,
 A     7
 B     7
 C    18
 dtype: object)

In [182]:
df,df.size

(   A    B
 0  1  3.0
 1  2  4.0
 2  3  NaN,
 6)

In [184]:
df.empty

False

In [194]:
df.T.columns,df.T.index

(RangeIndex(start=0, stop=3, step=1), Index(['A', 'B'], dtype='object'))

In [200]:
df.values

array([[ 1.,  3.],
       [ 2.,  4.],
       [ 3., nan]])

In [208]:
df['A'].values.tolist(),df['A'].values

([1, 2, 3], array([1, 2, 3], dtype=int64))

In [212]:
dict1 = {'A':1,'B':2}
dict2 = {'C':20,'B':10}
{**dict1,**dict2}

{'A': 1, 'B': 10, 'C': 20}

In [219]:
df.shape[0]

3

In [225]:
lst =[['1',2,3],[4,5,6],[7,4,9]]
df=pd.DataFrame(lst)
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  4  9