# Dataframe.Groupby

In [69]:
import pandas as pd
import numpy as np
import warnings
# Suppress all warnings
warnings.filterwarnings("ignore")

GroupBy in Pandas is a powerful feature that allows you to group data and perform operations on these groups. This feature is similar to the SQL group by statement. In Pandas, GroupBy can be used to group data in many different ways and perform complex data transformations and analysis.The agg() function is commonly used with groupby() in pandas to apply multiple aggregation functions to grouped data. This allows you to compute summary statistics such as sum, mean, count, etc., for each group.

Common Use Cases
- Aggregating Data: Compute summary statistics (e.g., sum, mean) for grouped data.
- Transforming Data: Perform transformations (e.g., normalization) on grouped data.
- Filtering Data: Filter groups based on a condition.

pandas.DataFrame.groupby syntax 

DataFrame.groupby(by=None, axis=_NoDefault.no_default, level=None, as_index=True, sort=True, group_keys=True, observed=_NoDefault.no_default, dropna=True)upBy object

#### Parameters
- by: mapping, function, str, or iterable
- axis : int, default 0
  
- level : If the axis is a MultiIndex (hierarchical), group by a particular level or levels
  
- as_index : For aggregated output, return object with group labels as the index. Only relevant for DataFrame input. as_index=False is   effectively “SQL-style” grouped output
  
- sort : Sort group keys. Get better performance by turning this off. Note this does not influence the order of observations within each -group. groupby preserves the order of rows within each group.
  
- group_keys : When calling apply, add group keys to index to identify pieces
  
- squeeze : Reduce the dimensionality of the return type if possible, otherwise return a consistent type
  
- Returns : GroupBy object

#### Consider the below example Consisting of The Details of employees

In [124]:
data = {
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'HR'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace'],
    'Salary': [50000, 60000, 55000, 70000, 65000, 62000, 58000],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F']
}

df = pd.DataFrame(data)
df

  Department Employee  Salary Gender
0         HR    Alice   50000      F
1         IT      Bob   60000      M
2         HR  Charlie   55000      M
3         IT    David   70000      M
4    Finance      Eva   65000      F
5    Finance    Frank   62000      M
6         HR    Grace   58000      F

#### Use of agg() function
The agg() function is commonly used with groupby() in pandas to apply multiple aggregation functions to grouped data. This allows you to compute summary statistics such as sum, mean, count, etc., for each group.

In [127]:
df[['Department','Salary']].groupby(by=['Department']).agg(sum)

            Salary
Department
Finance     127000
HR          163000
IT          130000

#### use of reset index function

In pandas, when you use groupby(), the grouped columns typically become the index of the resulting DataFrame. The reset_index() function is used to turn the groupby result back into a standard DataFrame by moving the index (the grouped columns) back into regular columns.

In [147]:
df[['Department','Salary']].groupby(by=['Department'],as_index=False).agg(sum)

  Department  Salary
0    Finance  127000
1         HR  163000
2         IT  130000

# Understanding the arguments

## "by" Argument

In Python's pandas library, the by argument in the groupby() function is used to specify the key or keys by which the data should be grouped. These keys can be:

- Column names: You can group the data based on one or more columns in the DataFrame.
- A function: You can pass a function that defines how to group the data.
- A list or array: You can pass an external list or array that indicates the group for each row.

In [92]:
data = {
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'HR'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace'],
    'Salary': [50000, 60000, 55000, 70000, 65000, 62000, 58000],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F']
}

df = pd.DataFrame(data)

#### Original Data Frame

In [59]:
df

  Department Employee  Salary Gender
0         HR    Alice   50000      F
1         IT      Bob   60000      M
2         HR  Charlie   55000      M
3         IT    David   70000      M
4    Finance      Eva   65000      F
5    Finance    Frank   62000      M
6         HR    Grace   58000      F

#### Single string as input to by argument
You can pass the name of a single column by which the operation should be performed.

In [121]:
df[['Department','Salary']].groupby(by="Department").agg(sum).reset_index()

  Department  Salary
0    Finance  127000
1         HR  163000
2         IT  130000

#### List of column names as input to by argument
If you want to perform the operation on multiple columns, you can pass a list of column names.

In [93]:
df[['Department','Gender','Salary']].groupby(by=["Department","Gender"]).agg(sum).reset_index()

  Department Gender  Salary
0    Finance      F   65000
1    Finance      M   62000
2         HR      F  108000
3         HR      M   55000
4         IT      M  130000

## Multi index

### Understanding the 'level' argument requires first familiarizing ourselves with the concept of multiindexing.

- Multi-index allows you to represent data with multi-levels of indexing, creating a hierarchy in rows and columns.
- It is a multi-level or hierarchical object for Pandas object.
- 
We can use various methods of multi-index such as MultiIndex.from_arrays(), MultiIndex.from_tuples(), MultiIndex.from_product(), MultiIndex.from_frame, etc., which helps us to create multiple indexes from arrays, tuples, DataFrame, et

Please refer to below link to understand more about multi index:   
https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html
c.

#### Multiindex from arrays

In [225]:
arrays=[['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'HR'], ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace']]
data = {
#    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'HR'],
#    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace'],
    'Salary': [50000, 60000, 55000, 70000, 65000, 62000, 58000],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F']
}
index=pd.MultiIndex.from_arrays(arrays, names=('Department', 'Employee'))
df2 = pd.DataFrame(data=data, index=index)
df2

                     Salary Gender
Department Employee
HR         Alice      50000      F
IT         Bob        60000      M
HR         Charlie    55000      M
IT         David      70000      M
Finance    Eva        65000      F
           Frank      62000      M
HR         Grace      58000      F

#### Multiindex from tuples

In [226]:
tuples=[('HR','Alice'),('IT','Bob'), ('HR','Charlie'),('IT','David'),('Finance','Eva'),('Finance','Frank'),('HR','Grace')]
data = {
#    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'HR'],
#    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace'],
    'performance': [90,95,89,97,95, 85,99],
    'Marital Status': ['Y', 'N', 'N', 'Y', 'Y', 'N', 'N']
}
index=pd.MultiIndex.from_tuples(tuples, names=('Department', 'Employee'))
df3 = pd.DataFrame(data=data, index=index)
df3

                     performance Marital Status
Department Employee
HR         Alice              90              Y
IT         Bob                95              N
HR         Charlie            89              N
IT         David              97              Y
Finance    Eva                95              Y
           Frank              85              N
HR         Grace              99              N

### Applications of Multi level index
A MultiIndexed DataFrame, also known as a hierarchical index, in pandas is particularly useful in scenarios where your dataset naturally has multiple levels of grouping or classification. Here are some practical use cases:

#### 1)Joining Based on Index
Given two multi-indexed dataframes with identical indices—Department and employee name—the first dataframe includes the features salary and gender, while the second contains employee performance and marital status.

use case: If we require a consolidation all this information into a single dataframe, we can join the two dataframes based on their common indices of the multiindexed dataframes.
##### Input Dataframes

In [234]:
df2

                     Salary Gender
Department Employee
HR         Alice      50000      F
IT         Bob        60000      M
HR         Charlie    55000      M
IT         David      70000      M
Finance    Eva        65000      F
           Frank      62000      M
HR         Grace      58000      F

In [235]:
df3

                     performance Marital Status
Department Employee
HR         Alice              90              Y
IT         Bob                95              N
HR         Charlie            89              N
IT         David              97              Y
Finance    Eva                95              Y
           Frank              85              N
HR         Grace              99              N

##### Output DataFrame after Joining

In [229]:
df2.join(df3)

                     Salary Gender  performance Marital Status
Department Employee
HR         Alice      50000      F           90              Y
IT         Bob        60000      M           95              N
HR         Charlie    55000      M           89              N
IT         David      70000      M           97              Y
Finance    Eva        65000      F           95              Y
           Frank      62000      M           85              N
HR         Grace      58000      F           99              N

#### 2)Hierarchical Product Catalogs
- Example: In retail, where products are categorized hierarchically (e.g., Category, Subcategory, Product).
- Usage: The MultiIndex helps in easily filtering and analyzing data at different levels, such as all products under a certain category, or specific subcategories.

#### 3)Geospatial Data
- Example: For geographic datasets where data is collected across different states, cities, and even neighborhoods:
First level: State.
Second level: City or neighborhood.
- Usage: This allows for analyses at different geographic resolutions.

In all these cases, multi-indexed DataFrames allow for easier manipulation, hierarchical slicing, and more organized data management when working with multi-dimensional data.

## "level" argument

In pandas, the level argument is used with the groupby() function to group data by the levels of a MultiIndex. It is useful when your DataFrame has a multi-level index (i.e., hierarchical indexing) and you want to group the data based on one or more levels of that index rather than the column values.

#### Note:
#### - Level name shoud match with any of the index in the DataFrame
#### - in a groupby function only one of the two arguments ("by","level") should be used.

In [205]:
data = {
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'HR'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace'],
    'Salary': [50000, 60000, 55000, 70000, 65000, 62000, 58000],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F']
}

df = pd.DataFrame(data)

#### Original Data Frame

In [59]:
df

  Department Employee  Salary Gender
0         HR    Alice   50000      F
1         IT      Bob   60000      M
2         HR  Charlie   55000      M
3         IT    David   70000      M
4    Finance      Eva   65000      F
5    Finance    Frank   62000      M
6         HR    Grace   58000      F

In [94]:
print("Consider the below multi level index DataFrame")
df1=df[['Department','Gender','Salary']].groupby(by=["Department","Gender"]).agg(sum)
df1

Consider the below multi level index DataFrame

                   Salary
Department Gender
Finance    F        65000
           M        62000
HR         F       108000
           M        55000
IT         M       130000

#### The output when level = 0

In [97]:
df1.groupby(level=0).agg(sum)

            Salary
Department
Finance     127000
HR          163000
IT          130000

#### The output when level =1

In [102]:
df1.groupby(level=1).agg(sum)

        Salary
Gender
F       173000
M       247000

##  "as_index" argument
In Pandas, the as_index parameter in the groupby() function controls whether the group labels (i.e., the values used to group the data) are kept as an index in the resulting DataFrame.

- as_index=True (default): The group labels are used as the index in the result. This means that the resulting DataFrame will have the group labels as its row index.

- as_index=False: The group labels are not set as the index; instead, they are kept as regular columns in the resulting DataFrame. This is often useful when you want to reset the index and have a more "flat" DataFrame structure, making it easier to work with the grouped results.

In [104]:
data = {
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'HR'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace'],
    'Salary': [50000, 60000, 55000, 70000, 65000, 62000, 58000],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F']
}

df = pd.DataFrame(data)

#### Original Data Frame

In [105]:
df

  Department Employee  Salary Gender
0         HR    Alice   50000      F
1         IT      Bob   60000      M
2         HR  Charlie   55000      M
3         IT    David   70000      M
4    Finance      Eva   65000      F
5    Finance    Frank   62000      M
6         HR    Grace   58000      F

#### Output when as_index = True

In [109]:
df[['Department','Gender','Salary']].groupby(by=["Department","Gender"],as_index=True).agg(sum)

                   Salary
Department Gender
Finance    F        65000
           M        62000
HR         F       108000
           M        55000
IT         M       130000

#### Output when as_index = False

In [110]:
df[['Department','Gender','Salary']].groupby(by=["Department","Gender"],as_index=False).agg(sum)

  Department Gender  Salary
0    Finance      F   65000
1    Finance      M   62000
2         HR      F  108000
3         HR      M   55000
4         IT      M  130000

## "sort" argument
The sort parameter in Pandas' groupby() function controls whether the group keys (i.e., the values used to group the data) are sorted or not in the resulting DataFrame.

- sort=True (default): The group keys are sorted in ascending order. This means the grouped data will be arranged by the group labels in sorted order.

- sort=False: The group keys are not sorted, and the original order of the group labels in the data is preserved.

In [116]:
data = {
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'HR'],
#    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace'],
    'Salary': [50000, 60000, 55000, 70000, 65000, 62000, 58000],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F']
}

df = pd.DataFrame(data)

#### Original Data Frame

In [117]:
df

  Department  Salary
0         HR   50000
1         IT   60000
2         HR   55000
3         IT   70000
4    Finance   65000
5    Finance   62000
6         HR   58000

#### Output when Sort = False

In [119]:
df.groupby(by=["Department"],sort=False).agg(sum)

            Salary
Department
HR          163000
IT          130000
Finance     127000

#### Output when Sort = True

In [120]:
df.groupby(by=["Department"],sort=True).agg(sum)

            Salary
Department
Finance     127000
HR          163000
IT          130000

# Aggregation functions

Aggregation functions in a groupby operation are used to summarize data by applying a function to groups of data. When you group data by one or more columns, you can use aggregation functions to compute statistics like sums, means, counts, etc., for each group. Some common aggregation functions include:
- sum(): Returns the sum of the values for each group.
- mean(): Returns the mean (average) of the values for each group.
- median(): Returns the median of the values for each group.
- count(): Returns the number of non-null values for each group.
- size(): Returns the size of each group (includes NaN values).
- min(): Returns the minimum value of each group.
- max(): Returns the maximum value of each group.
- std(): Returns the standard deviation of each group.
- var(): Returns the variance of each group.
- prod(): Returns the product of the values for each group.
- describe(): Returns summary statistics for each group (count, mean, std, min, max, etc.).
- agg() or aggregate(): Apply multiple aggregation functions to columns. Can use predefined functions or custom functions.

# Transformation Functions

## DataFrame.Groupby.rank

Methods:
- average: the average rank of group.
- min: lowest rank in group.
- max: highest rank in group.
- first: ranks assigned in order they appear in the array.
- dense: like ‘min’, but rank always increases by 1 between groups.

please refer to the below link to understand more regarding the rank function in groupby:
https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.rank.html

In [244]:
data = {
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'HR'],
    'Employee': ['Grace', 'Bob', 'Charlie', 'David', 'Eva', 'Frank','Alice'],
    'Salary': [50000, 60000, 55000, 70000, 65000, 62000,50000],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F']
}

df = pd.DataFrame(data)

#### Original Data Frame

In [245]:
df

  Department Employee  Salary Gender
0         HR    Grace   50000      F
1         IT      Bob   60000      M
2         HR  Charlie   55000      M
3         IT    David   70000      M
4    Finance      Eva   65000      F
5    Finance    Frank   62000      M
6         HR    Alice   50000      F

In [254]:
df["Average Rank"]=df[['Department','Salary']].groupby(by=["Department"]).rank(method='average')
df["Lowest Rank"]=df[['Department','Salary']].groupby(by=["Department"]).rank(method='min')
df["Highest Rank"]=df[['Department','Salary']].groupby(by=["Department"]).rank(method='max')
df["First Rank"]=df[['Department','Salary']].groupby(by=["Department"]).rank(method='first')
df["Dense Rank"]=df[['Department','Salary']].groupby(by=["Department"]).rank(method='dense')

#### The Output for all the different methods available in Rank function
method for ranking refers to how the ranks are assigned when there are tied values(multiple items with the same value) within a group.
1) Average
   - the average method assigns the average of the ranks that would have been assigned to those tied values.
2) min
   - the min method assigns the smallest rank to all tied values.
3) max
   - the max method assigns the highest rank to all tied values.
4) first
   -  the first method assigns ranks based on the order in which the tied values appear in the original data.
5) dense
   - the dense method assigns the same rank to all tied values. The next distinct value gets the next consecutive rank, without skipping any rank values.

In [253]:
df

,Department,Employee,Salary,Gender,Average Rank,Lowest Rank,Highest Rank,First Rank,Dense Rank
0,HR,Grace,50000,F,1.5,1.0,2.0,1.0,1.0
1,IT,Bob,60000,M,1.0,1.0,1.0,1.0,1.0
2,HR,Charlie,55000,M,3.0,3.0,3.0,3.0,2.0
3,IT,David,70000,M,2.0,2.0,2.0,2.0,2.0
4,Finance,Eva,65000,F,2.0,2.0,2.0,2.0,2.0
5,Finance,Frank,62000,M,1.0,1.0,1.0,1.0,1.0
6,HR,Alice,50000,F,1.5,1.0,2.0,2.0,1.0

### Applications of Different methods of Groupby.rank function

#### 1)First Rank

##### Use case: Competition Ranking
- Problem: A coding competition is being held, where participants submit their answers, and the results are stored in the order of submission. The examiners notice that the scores for the participants in 3rd and 4th positions are tied, causing confusion about how to determine the top 3 performers. How should the top 3 be decided in this situation ?
  
- solution:we can solve the above problem statement using "first rank" method which ranks participants based on their score and the order in which they submitted, giving priority to the one who submitted earlier in case of a tie.

we will try to understand this using an example dataset:
The dataset includes records of competitions across three coding languages, detailing each participant’s name, the language they were tested on, and their results, with submissions recorded in order. Given that some participants have identical scores, how can the examiners identify the top 3 performers within each group?

In [277]:
result_data = {
    'Language':['python','c','python','java','c','java','python','java','python','java','c','python','java'],
    'Participant': ['Grace', 'Bob', 'Charlie', 'David', 'Eva', 'Frank','Alice','Charles','John','Jim','Tom','Sam','Ben'],
    'Score': [98,99,95,96,98,95,95,94,96,94,96,93,92]
}
comp_results=pd.DataFrame(result_data)
comp_results

   Language Participant  Score
0    python       Grace     98
1         c         Bob     99
2    python     Charlie     95
3      java       David     96
4         c         Eva     98
5      java       Frank     95
6    python       Alice     95
7      java     Charles     94
8    python        John     96
9      java         Jim     94
10        c         Tom     96
11   python         Sam     93
12     java         Ben     92

In [279]:
comp_results["First Rank"]=comp_results[["Language","Score"]].groupby(by="Language").rank(method="first",ascending=False)
comp_results

   Language Participant  Score  First Rank
0    python       Grace     98         1.0
1         c         Bob     99         1.0
2    python     Charlie     95         3.0
3      java       David     96         1.0
4         c         Eva     98         2.0
5      java       Frank     95         2.0
6    python       Alice     95         4.0
7      java     Charles     94         3.0
8    python        John     96         2.0
9      java         Jim     94         4.0
10        c         Tom     96         3.0
11   python         Sam     93         5.0
12     java         Ben     92         5.0

##### Refer to the output below for Python Language
Considering Python Language,If we use First Rank when assigning ranks to two participants, Charlie and Alice, both with a score of 95, Charlie will be ranked higher than Alice as his submission was earlier. this helps in making fair judgement between the two.
###### - Note: In the below example we have used get_group function in groupby,use the link below to understand more about it
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.get_group.html

In [280]:
comp_results.groupby(by='Language').get_group("python")

   Language Participant  Score  First Rank
0    python       Grace     98         1.0
2    python     Charlie     95         3.0
6    python       Alice     95         4.0
8    python        John     96         2.0
11   python         Sam     93         5.0

#### 2)Dense Rank

##### Use case: Awarding the Top 3 Mark Achievers
- Problem:A university wants to recognize and award students who have secured the top three highest marks. The faculty needs to identify and select all the students who have achieved these top three scores.
Which method would you suggest to help the faculty efficiently retrieve the list of students who have secured the top three marks?

- solution:We can solve the problem using the Dense Rank method, which ranks students based on their marks. When multiple students have the same score, they are assigned the same rank. However, unlike regular ranking methods, the Dense Rank ensures that the ranks remain consecutive, meaning no ranks are skipped.
  
we will try to understand this using an example dataset:
The dataset includes records of examinations across three Engineering Branches, detailing each student’s name, the Branch they belong to, and their exam results. Given that some students have identical scores, how can the faculty efficiently retrieve the list of students who have secured the top three marks?

In [291]:
result_data = {
    'Branch':['CSE','ECE','CSE','MECH','ECE','MECH','CSE','MECH','CSE','MECH','ECE','CSE','MECH'],
    'Student': ['Grace', 'Bob', 'Charlie', 'David', 'Eva', 'Frank','Alice','Charles','John','Jim','Tom','Sam','Ben'],
    'Marks': [98,99,95,96,98,95,96,94,96,94,96,93,92]
}
exam_results=pd.DataFrame(result_data)
exam_results

   Branch  Student  Marks
0     CSE    Grace     98
1     ECE      Bob     99
2     CSE  Charlie     95
3    MECH    David     96
4     ECE      Eva     98
5    MECH    Frank     95
6     CSE    Alice     96
7    MECH  Charles     94
8     CSE     John     96
9    MECH      Jim     94
10    ECE      Tom     96
11    CSE      Sam     93
12   MECH      Ben     92

In [288]:
exam_results["Dense Rank"]=exam_results[["Branch","Marks"]].groupby(by="Branch").rank(method="dense",ascending=False)
exam_results

   Branch  Student  Marks  Dense Rank
0     CSE    Grace     98         1.0
1     ECE      Bob     99         1.0
2     CSE  Charlie     95         3.0
3    MECH    David     96         1.0
4     ECE      Eva     98         2.0
5    MECH    Frank     95         2.0
6     CSE    Alice     96         2.0
7    MECH  Charles     94         3.0
8     CSE     John     96         2.0
9    MECH      Jim     94         3.0
10    ECE      Tom     96         3.0
11    CSE      Sam     93         4.0
12   MECH      Ben     92         4.0

##### Refer to the output below for CSE Branch
Considering CSE Branch,If we use Dense Rank when assigning ranks to two students who share the second-highest score, both will be ranked as 2nd, and the next student will be ranked 3rd (instead of 4th). This approach ensures that all students who achieve the top three marks, even if they tie, are recognized and awarded.

In [290]:
exam_results.groupby(by='Branch').get_group("CSE")

   Branch  Student  Marks  Dense Rank
0     CSE    Grace     98         1.0
2     CSE  Charlie     95         3.0
6     CSE    Alice     96         2.0
8     CSE     John     96         2.0
11    CSE      Sam     93         4.0

<!-- #### 1)Average Rank
##### Use case: Sales Performance Ranking
- Scenario: You are ranking sales agents based on their quarterly sales figures. Sometimes, agents have exactly the same sales figures (tied values).
- Ranking Method: If two agents tie for 2nd place, instead of giving both 2nd and 3rd place, the average method assigns both of them rank 2.5.
- Result: Both agents are ranked 2.5 for fairness and simplicity in reporting tied performances.

#### 2)min Rank
##### Use case: Product Defect Rates
- Scenario: You are ranking manufacturing plants based on their defect rates, with some plants having identical rates.
- Ranking Method: You want to emphasize the lowest rank for tied plants. So if two plants tie with the lowest defect rate, both receive rank 1.
- Result: All tied plants will share the lowest rank available in that group, which can highlight excellent performance.

#### 3)max Rank
##### Use case: Employee Salary Rankings
- Scenario: You are ranking employees based on their salaries within departments. Some employees have the same salary.
- Ranking Method: You want to emphasize the highest rank in the case of ties. If two employees tie for 2nd place, both are given rank 3.
- Result: Both employees will be ranked as if they are the last in the group for that rank, useful when focusing on how far they can be ranked up.

#### 4)First Rank
##### Use case: Competition Ranking
- Scenario: You're processing a leaderboard where the order of submissions or actions is significant (e.g., speed-based competitions like hackathons or coding contests).
- Ranking Method: The First method ensures that the record making the first entry is considered with priority during ranking even if the scores are of same value.
- Result: This method helps if you want to maintain the importance of the sequence of actions, such as in situations where a faster response or submission is critical.

#### 5)dense Rank
##### Use Case: University GPA Ranking
- Scenario: You are ranking students based on their GPA across different departments. You want to ensure that the ranking numbers are consecutive without gaps between them.
- Ranking Method: The dense method ensures no gaps in the rank numbers. If two students tie for 2nd place, both are ranked 2, but the next rank is 3 (not 4).
- Result: Ensures that ranking numbers are compact and consistent without skipping ranks, useful for official academic ranking publications.
 -->

## DataFrame.Groupby.filter

- groupby.filter is used to filter out entire groups based on a condition. It works on data that has been grouped by one or more columns using groupby(), and it evaluates a function for each group. If the group meets the condition, it is kept in the output; otherwise, it is removed.
##### Syntax: 
DataFrame.groupby('column_name').filter(function)

- use the hyperlink for more information
  https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.filter.html

#### Application of groupby.filter:
problem:
You manage a chain of retail stores that sell various products across different categories. Each store reports its sales data for each product sold in a particular month. The objective is to identify the best-performing stores for the month, based on the total sales they achieved across all products.The task is to filter out the top-performing stores where the total sales for the month exceed a given threshold.

Solution:
one way to solve this is by using the filter function along with groupby. You can set a sales threshold and then filter out any groups where the total sales exceed that threshold.
consider threshold to be $25000 and the result shows that only store A and store C have the total sales value more than this threshold

In [362]:
sales_data= {
    'Store': ['Store_A', 'Store_A', 'Store_A', 'Store_B', 'Store_B', 'Store_B', 
              'Store_C', 'Store_C', 'Store_C', 'Store_D', 'Store_D', 'Store_D'],
    'Product': ['Product_1', 'Product_2', 'Product_3', 'Product_4', 'Product_5', 'Product_6', 
                'Product_7', 'Product_8', 'Product_9', 'Product_10', 'Product_11', 'Product_12'],
    'Category': ['Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 
                 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing'],
    'Month': ['Sep-2024']*12,
    'Sales': [12000, 8000, 10000, 7000, 6000, 9000, 22000, 15000, 10000, 9000, 8000, 6000]

            }

df = pd.DataFrame(sales_data)
sales_threshold = 25000

# Group by Store and filter based on total sales greater than the threshold
best_stores = df.groupby('Store').filter(lambda x: x['Sales'].sum()>sales_threshold)
best_stores

     Store    Product     Category     Month  Sales
0  Store_A  Product_1  Electronics  Sep-2024  12000
1  Store_A  Product_2    Furniture  Sep-2024   8000
2  Store_A  Product_3     Clothing  Sep-2024  10000
6  Store_C  Product_7  Electronics  Sep-2024  22000
7  Store_C  Product_8    Furniture  Sep-2024  15000
8  Store_C  Product_9     Clothing  Sep-2024  10000

## Cumulative functions

### cumsum

groupby().cumsum() in pandas is used to calculate the cumulative sum of values within each group in a DataFrame. It is an extension of the groupby() functionality, where after grouping data by one or more columns, the cumulative sum (cumsum()) is calculated for each group separately.

#### Practical Use case of Cumsum
##### Problem Statement:
- You are tasked with analyzing the performance of players in the Indian Premier League (IPL) across several matches during the season. You have data showing how many runs each player has scored in each match. Your objective is to determine which players have contributed the most consistently over the season by tracking their performance across matches.

##### solution:
- To solve this, a good approach is to calculate the cumulative total of runs for each player over the course of the season. This allows    you to:
  - Track how many runs each player has scored up to any given match.
  - Compare players based on their overall contributions after each match.
  - Observe trends in performance, such as consistency or improvement over time.

Consider the below example containing the data of player along with the match number along with the number of runs scored correspondingly.

In [ ]:
data = {
    'Player': ['Player A', 'Player A', 'Player A', 'Player B', 'Player B', 'Player C'],
    'Match': [1, 2, 3, 1, 2, 1],
    'Runs': [45, 30, 50, 20, 60, 40]
}
df=pd.DataFrame(data)
df

to determine the performance accross different matches we can track using cumulative sum,It shows how the player's total runs have accumulated over the season as they play more matches. For example, if a player scores 45 runs in the first match and 30 runs in the second match, the cumulative total after the second match will be 75. This provides insight into the player's consistency and performance throughout the season.

In [339]:
df['Cumulative_Runs'] = df.groupby('Player')['Runs'].cumsum()
df

     Player  Match  Runs  Cumulative_Runs
0  Player A      1    45               45
1  Player A      2    30               75
2  Player A      3    50              125
3  Player B      1    20               20
4  Player B      2    60               80
5  Player C      1    40               40

### cumcount

cumcount() is a function in pandas that returns the cumulative count of occurrences of each unique value in a column or a group. It is often used in data manipulation when you need to create a cumulative sequence number for repeated values within a group.
##### Note: The count begins at 0, but you can adjust it to start at 1(by adding 1) if necessary.
#### Practical Use case of Cumcount
##### Problem Statement:
You are working for an e-commerce platform and need to analyze customer purchase behavior. Each customer can place multiple orders, and the dataset contains a record of each order placed by a customer. The goal is to determine how many purchases each customer has made up to and including each transaction to track their engagement and frequency of orders over time.
##### solution:
To solve this, we can use the cumcount() function to generate a running total of purchases for each customer. This will help us track how many times each customer has made a purchase as of any given order.

Assume the below dataset that contains customer IDs and their order dates or order numbers.

In [342]:
data = {
    'Customer_ID': ['C001', 'C001', 'C001', 'C002', 'C002', 'C003'],
    'Order_Date': ['2023-01-15', '2023-02-20', '2023-03-10', '2023-01-18', '2023-03-05', '2023-01-25']
}

df = pd.DataFrame(data)
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df

  Customer_ID Order_Date
0        C001 2023-01-15
1        C001 2023-02-20
2        C001 2023-03-10
3        C002 2023-01-18
4        C002 2023-03-05
5        C003 2023-01-25

- For this problem statement cumcount() function is highly useful for tracking the purchase behavior of each customer over time. Specifically, it allows you to count how many purchases a customer has made up to and including each transaction.
- By observing how the "Purchase Count" progresses for each transaction, you can see how frequently the customer buys products. If the purchase count increases rapidly, it indicates that the customer is making frequent purchases in a short period.

In [347]:
df['Purchase_Count'] = df.groupby('Customer_ID').cumcount()+1
df

  Customer_ID Order_Date  Purchase_Count
0        C001 2023-01-15               1
1        C001 2023-02-20               2
2        C001 2023-03-10               3
3        C002 2023-01-18               1
4        C002 2023-03-05               2
5        C003 2023-01-25               1

### cum min

- This function calculates the cumulative minimum of a column or a Series. It means that at any given index i, the value is the smallest value seen so far in the sequence (from the beginning up to that index).
For example, for a sequence [3, 1, 4, 2], the cumulative minimum would be [3, 1, 1, 1].
- When you use cummin() after groupby(), pandas computes the cumulative minimum within each group independently. So for each group, the cumulative minimum calculation restarts from the first element of the group.
#### Practical Use case of Cummin
##### Problem Statement:
You are a financial analyst responsible for monitoring and reporting on stock prices for your company’s investment portfolio. Your manager has tasked you with developing a method to track the daily stock prices and, more importantly, to identify the lowest price observed up to each day.
##### solution:
We can use the cumulative minimum (cumulative min) function to keep track of the lowest stock price observed up to each date. This means that for each day, we will record the smallest stock price observed so far.

Assume the below dataset that contains stock information of some companies along with Date and price.

In [356]:
data = {
    'Company': ['AAPL', 'AAPL', 'AAPL', 'GOOG', 'GOOG', 'GOOG', 'AAPL', 'GOOG'],
    'Date': ['2023-09-20', '2023-09-21', '2023-09-22', '2023-09-20', '2023-09-21', '2023-09-22', '2023-09-23', '2023-09-23'],
    'Price': [150, 148, 151, 2800, 2750, 2780, 149, 2775]
}

df = pd.DataFrame(data)

df['Date'] = pd.to_datetime(df['Date'])
df

  Company       Date  Price
0    AAPL 2023-09-20    150
1    AAPL 2023-09-21    148
2    AAPL 2023-09-22    151
3    GOOG 2023-09-20   2800
4    GOOG 2023-09-21   2750
5    GOOG 2023-09-22   2780
6    AAPL 2023-09-23    149
7    GOOG 2023-09-23   2775

The column cumulative_min_price gives us insights on the variation of price from the minimum price till that point of time to analyze stocks

In [357]:
df['Cumulative_Min_Price'] = df.groupby('Company')['Price'].cummin()
df

  Company       Date  Price  Cumulative_Min_Price
0    AAPL 2023-09-20    150                   150
1    AAPL 2023-09-21    148                   148
2    AAPL 2023-09-22    151                   148
3    GOOG 2023-09-20   2800                  2800
4    GOOG 2023-09-21   2750                  2750
5    GOOG 2023-09-22   2780                  2750
6    AAPL 2023-09-23    149                   148
7    GOOG 2023-09-23   2775                  2750

### cum max

groupby.cummax is a method in Pandas that computes the cumulative maximum of a column or a set of columns for each group within a groupby object. It returns the maximum value encountered up to the current point in each group.

#### Practical Use case of Cummin
##### Problem Statement:
You are conducting an under water breath holding competition and analyzing the performance of swimmers, specifically tracking how long each swimmer can stay underwater during their training sessions. You want to monitor the maximum time each swimmer has managed to stay underwater after each session. This helps in evaluating endurance improvements or consistency in their performance over time.
##### solution:
We will group the data by swimmer and calculate their cumulative maximum underwater time after each session to track the longest duration they've managed to stay underwater up to that point.

The dataset provided includes records from an underwater breath-holding competition, detailing the date and the maximum duration each performer remained submerged.

In [378]:
data = {
    'Date': ['2024-06-01', '2024-06-10', '2024-06-15', '2024-06-20', 
             '2024-06-01', '2024-06-10', '2024-06-15', '2024-06-20'],
    'Swimmer': ['John', 'John', 'John', 'John', 'Emma', 'Emma', 'Emma', 'Emma'],
    'Underwater Time (seconds)': [600, 590, 660, 580, 670, 660, 630, 650]
}
df = pd.DataFrame(data)
df

         Date Swimmer  Underwater Time (seconds)
0  2024-06-01    John                        600
1  2024-06-10    John                        590
2  2024-06-15    John                        660
3  2024-06-20    John                        580
4  2024-06-01    Emma                        670
5  2024-06-10    Emma                        660
6  2024-06-15    Emma                        630
7  2024-06-20    Emma                        650


The cumulative max column represents the longest breath-holding duration achieved by a participant up to that point in the competition. By analyzing this data, we can track performance trends over time, identify potential plateaus, and assess whether additional practice or training is required to improve further. This analysis provides valuable insights into the participant's progress and areas for improvement.

In [379]:
df['Cumulative Max Underwater Time'] = df.groupby('Swimmer')['Underwater Time (seconds)'].cummax()
df

,Date,Swimmer,Underwater Time (seconds),Cumulative Max Underwater Time
0,2024-06-01,John,600,600
1,2024-06-10,John,590,600
2,2024-06-15,John,660,660
3,2024-06-20,John,580,660
4,2024-06-01,Emma,670,670
5,2024-06-10,Emma,660,670
6,2024-06-15,Emma,630,670
7,2024-06-20,Emma,650,670

## DataFrame.Groupby.apply

In Pandas, groupby.apply is a method used to apply a function to each group of a DataFrame after it has been grouped by one or more columns. This allows for more flexible data manipulation and aggregation compared to standard aggregation methods. 
#### Practical Use case of Groupby.apply
##### Problem Statement:
You are working with an employee dataset that includes details about employees, their departments, salaries, and performance ratings. Your task is to categorize each employee into one of three performance categories based on the following criteria:
- High Performer: An employee is considered a high performer if their performance rating is 4.0 or higher and their salary is above or equal to the median salary of their department.
- Average Performer: An employee is considered an average performer if they do not meet the criteria for high or low performers.
- Low Performer: An employee is considered a low performer if their performance rating is below 4.0 and their salary is below the median salary of their department.
###### Solution:
we can use groupby.apply function to solve these kind of problem statements.First,we create a function to categorize each employee based on their performance rating and salary and then apply that function to each group to perform this group wise.

In [382]:
import pandas as pd

# Step 1: Create a DataFrame with employee data
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Department': ['HR', 'HR', 'Finance', 'Finance', 'HR', 'Finance'],
    'Salary': [70000, 60000, 90000, 80000, 75000, 85000],
    'Performance Rating': [4.5, 3.0, 4.0, 2.5, 5.0, 3.5]
}

df = pd.DataFrame(data)
df

  Employee Department  Salary  Performance Rating
0    Alice         HR   70000                 4.5
1      Bob         HR   60000                 3.0
2  Charlie    Finance   90000                 4.0
3    David    Finance   80000                 2.5
4      Eva         HR   75000                 5.0
5    Frank    Finance   85000                 3.5

The Function categorize_performance takes each row in a group and assigns the output to the new column performance category based on their performance rating column
- if performance rating is greater than 4 then they are considered as "High Performer" and
- if they have performance rating less than 4 then "Low Performer"
- else an "Average Performer"

In [412]:
def categorize_performance(group):
    def performance_category(row):
        if row['Performance Rating'] > 4.0: 
            return 'High Performer'
        elif row['Performance Rating'] < 4.0: 
            return 'Low Performer'
        else:
            return 'Average Performer'
    
    group['Performance Category'] = group.apply(performance_category, axis=1)
    return group

In [415]:
result = df.groupby('Department').apply(categorize_performance).reset_index(drop=True)
result

  Employee Department  Salary  Performance Rating Performance Category
0  Charlie    Finance   90000                 4.0    Average Performer
1    David    Finance   80000                 2.5        Low Performer
2    Frank    Finance   85000                 3.5        Low Performer
3    Alice         HR   70000                 4.5       High Performer
4      Bob         HR   60000                 3.0        Low Performer
5      Eva         HR   75000                 5.0       High Performer