## DataFrame.all(axis=0, bool_only=False, skipna=True, **kwargs)

## The all() method returns one value for each column, True if ALL values in that column are True, otherwise False

In [2]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'c1': [True, True,np.nan], 'c2': [False, False,1]})
df

     c1     c2
0  True  False
1  True  False
2   NaN      1

In [3]:
df.all(bool_only=False,skipna=False)

c1     True
c2    False
dtype: bool

In [4]:
df.all(axis=1,bool_only=True)

0    True
1    True
2    True
dtype: bool

In [5]:
df.all(axis=0)

c1     True
c2    False
dtype: bool

In [6]:
import pandas as pd
df_1=pd.DataFrame([True,True])
df_2=pd.DataFrame([False,False])
df_3=pd.DataFrame([True,False])
df_4=pd.DataFrame([True,False],[True,False])
print(df_1.all())
print(df_2.all())
print(df_3.all())
print(df_4.all())

0    True
dtype: bool
0    False
dtype: bool
0    False
dtype: bool
0    False
dtype: bool

In [7]:
print(df_4)

           0
True    True
False  False

In [8]:
import pandas as pd

df = pd.DataFrame({
    'A': [True, True, False],
    'B': [False, True, True],
    'C': [True, True, True]
})


df 
#df.all(axis=0)
df.all(axis=1)

#returns series

0    False
1     True
2    False
dtype: bool

## null values

In [9]:
df= pd.DataFrame({
    'A': [True, False, np.nan],
    'B': [False, np.nan, True],
    'C': [np.nan, np.nan, np.nan]
})
df
#df.all(skipna=False)

       A      B   C
0   True  False NaN
1  False    NaN NaN
2    NaN   True NaN

## all() method by default treats NaN (Not a Number) as True (NaN is not equal to zero)

In [11]:
df.all(skipna=True)

A    False
B    False
C     True
dtype: bool

In [12]:
df_with_nan = pd.DataFrame({
    'A': [True, False, np.nan],
    'B': [False, np.nan, True],
    'C': [np.nan, np.nan, np.nan]
})

df_all_nan = df_with_nan.all(skipna=False)

print(df_all_nan)

A    False
B    False
C     True
dtype: bool

## condition

In [53]:
df_numeric = pd.DataFrame({
    'X': [1, 2, 3],
    'Y': [4, 5, 6],
    'Z': [7, 8, 9]
})

df_numeric

   X  Y  Z
0  1  4  7
1  2  5  8
2  3  6  9

In [54]:
df_condition = (df_numeric['X'] > 0).all()

print(df_condition)

True

In [16]:
(df > 0).all(axis=1)

0     True
1    False
2    False
dtype: bool

## filter values

In [14]:
import pandas as pd

# Sample DataFrame
data = {'A': [1, 2, -3],
        'B': [4, 0, 6],
        'C': [7, 8, 9]}

df = pd.DataFrame(data)
df

   A  B  C
0  1  4  7
1  2  0  8
2 -3  6  9

In [15]:
filtered_df = df[(df > 0).all(axis=1)]

print(filtered_df)

   A  B  C
0  1  4  7

In [51]:
import pandas as pd

# Sample DataFrame
data = {
    'X': [1, 2, 3],
    'Y': [4, 5, 6],
    'Z': [7, 8, 9]
}

df = pd.DataFrame(data)
df

   X  Y  Z
0  1  4  7
1  2  5  8
2  3  6  9

In [52]:
filtered_df = df[(df > 0).all(axis=1)]

print(filtered_df)

   X  Y  Z
0  1  4  7
1  2  5  8
2  3  6  9

In [30]:
import pandas as pd
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8]
}
df5= pd.DataFrame(data)

In [4]:
df6

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [5]:
df6.add(1)

   A  B
0  2  6
1  3  7
2  4  8
3  5  9

In [9]:
df6.add([1,2])

   A   B
0  2   7
1  3   8
2  4   9
3  5  10

In [13]:
series=pd.Series([1,2,3,4])

In [14]:
series

0    1
1    2
2    3
3    4
dtype: int64

In [18]:
df6.add(series,axis=0)

   A   B
0  2   6
1  4   8
2  6  10
3  8  12

In [24]:
df7=pd.DataFrame({"C":[1,2,3,4],"D":[3,4,5,6]})

In [25]:
df7

   C  D
0  1  3
1  2  4
2  3  5
3  4  6

In [31]:
df6+df7+df5

    A   B   C   D
0 NaN NaN NaN NaN
1 NaN NaN NaN NaN
2 NaN NaN NaN NaN
3 NaN NaN NaN NaN