## eval()

## evaluates a string expression on the DataFrame columns.It allows you to perform calculations, create new columns, and filter data using string expressions.Operates on columns only, not specific rows or elements.

In [11]:
import pandas as pd

# Sample DataFrame
data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)
df

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [13]:
result = df.eval('C = A + B')    # returns a new dataframe
print(result)

   A   B   C
0  1  10  11
1  2  20  22
2  3  30  33
3  4  40  44
4  5  50  55

In [20]:
df.eval('C=A+B',inplace=True)   # using inplace we make changes in existing dataframe
df

   A   B   C   D   E
0  1  10  11  12  11
1  2  20  22  24  22
2  3  30  33  36  33
3  4  40  44  48  44
4  5  50  55  60  55

### Multiple columns can be assigned

In [18]:
df.eval('''
        D=C+A
        E=D-A
        ''',inplace=True)

In [19]:
df

   A   B   C   D   E
0  1  10  11  12  11
1  2  20  22  24  22
2  3  30  33  36  33
3  4  40  44  48  44
4  5  50  55  60  55