## pandas.DataFrame.apply(func, axis=0, raw=False, result_type=None, args=(), by_row='compat', engine='python', engine_kwargs=None, **kwargs)

1. apply function along axis of dataframe(entire row/col,single row/col)
2. obj passed to func=series objects(dataframe_axis=0(columns)/dataframe_axis=1(rows))
3. return type:series/dataframe

## Applying a Function to DataFrame Elements

In [2]:
#built_in_fns
import pandas as pd
import numpy as np
df = pd.DataFrame([[4, 9],[2,5]], columns=['A', 'B'])
#df
df.apply(np.square)

    A   B
0  16  81
1   4  25

In [3]:
#user_defined_fns
import pandas as pd
df = pd.DataFrame({'A': [1, 2], 'B': [10, 20]})
def square(x):
    return x * x
df.apply(square)

   A    B
0  1  100
1  4  400

## apply() with lambda

In [4]:
df.apply(lambda x: x * x)

   A    B
0  1  100
1  4  400

## apply() along axis

In [5]:
# (axis=0):across_all_cols(default)
# (axis=1):across_all_rows

import pandas as pd
import numpy as np
df = pd.DataFrame([[4, 9],[2,5]], columns=['A', 'B'])
#df
df.apply(np.square,axis=0)#across_all_col
#df.apply(np.square,axis=1)#across_all_row

    A   B
0  16  81
1   4  25

## apply() with arguments

In [59]:
import pandas as pd


def sum(x,y,z):
    return x+y+z
df = pd.DataFrame({'A': [1, 2], 'B': [10, 20]})
#df
df.apply(sum,args=(1, 2))

   A   B
0  4  13
1  5  23

In [67]:
import pandas as pd


def sum(x,y,z,**kwargs):
    return x+y+z+kwargs
df = pd.DataFrame({'A': [1, 2], 'B': [10, 20]})
#df
df.apply(sum,args=(1, 2),c=1,d=1)

TypeError: unsupported operand type(s) for +: 'int' and 'dict'

In [71]:
import pandas as pd

def sum_with_kwargs(x, y, z,t, **kwargs):
    return x + y + z +t+ kwargs['c'] + kwargs['d']
    #args cant have same var name as kwargs dict key

df = pd.DataFrame({'A': [1, 2], 'B': [10, 20]})

result = df.apply(sum_with_kwargs, args=(1, 2, 1), c=1, d=1)
print(result)

   A   B
0  7  16
1  8  26

In [60]:
import pandas as pd


def sum(x,y,z):
    return x+y+z
df = pd.DataFrame({'A': [1, 2], 'B': [10, 20]})
#df
df.apply(sum,**kwargs={'c':1,'d':2})

SyntaxError: invalid syntax (1229029049.py, line 8)

## apply() with positional and keyword arguments

In [36]:
#positional arg:args=(1,2)
#keyword arg:m=10
import pandas as pd
def sum(x, y, z, m):
    return (x + y + z) * m


df = pd.DataFrame({'A': [1, 2], 'B': [10, 20]})
df.apply(sum, args=(1, 2), m=10)

    A    B
0  40  130
1  50  230

In [37]:
import pandas as pd

# Define a custom function to be applied
def custom_function(x, a=1, b=1):
    return (x + a) * b

# Create a DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [10, 20, 30]})

# Apply the custom function to each column of the DataFrame
result = df.apply(custom_function, axis=0, raw=False, result_type='expand', args=(2,), by_row='compat', engine='python', engine_kwargs=None, a=10, b=5)

print(result)

TypeError: custom_function() got an unexpected keyword argument 'engine'

In [38]:
import pandas as pd

# Define a custom function to be applied
def custom_function(x, a=1, b=1):
    return (x + a) * b

# Create a DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [10, 20, 30]})

# Apply the custom function to each column of the DataFrame
result = df.apply(custom_function, axis=0, raw=False, result_type='expand', args=(2,), by_row='compat', a=10, b=5)

print(result)

TypeError: custom_function() got multiple values for argument 'a'

In [44]:
import pandas as pd

# Define a custom function to be applied
def custom_function(x, a=1, b=1):
    return (x + a) * b

# Create a DataFrame
df = pd.DataFrame({'A': [1, 2, 3,7], 'B': [10, 20, 30,40]})

# Apply the custom function to each column of the DataFrame
result = df.apply(custom_function, axis=1, raw=False, result_type='broadcast', by_row=True, a=10, b=5)

print(result)

ValueError: by_row=True not allowed

In [45]:
s1 = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])
s1

   A  B
0  4  9
1  4  9
2  4  9

In [ ]:
s1.apply()

In [50]:
def sum1(*args):
    return sum(args)

s1.apply(sum1, args=(1, 2, 3, 4, 5),raw=True)

RecursionError: maximum recursion depth exceeded

In [52]:
import pandas as pd

# Create the DataFrame
s1 = pd.DataFrame([[4, 9]], columns=['A', 'B'])

# Define the custom function to sum elements along with additional arguments
def sum_with_args(x, *args):
    return sum(x) + sum(args)

# Apply the custom function to each element of the DataFrame
result = s1.apply(lambda x: sum_with_args(x, 1, 2, 3, 4, 5))

print(result)

RecursionError: maximum recursion depth exceeded

## Set to true if the row/column should be passed as an ndarray object

In [72]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Define a custom function to be applied
def custom_function(row):
    return row.sum()

# Apply the custom function with raw=False (default)
result_default = df.apply(custom_function)
print("With raw=False:")
print(result_default)

# Apply the custom function with raw=True
result_raw = df.apply(custom_function, raw=True)
print("\nWith raw=True:")
print(result_raw)

With raw=False:
A     6
B    15
dtype: int64

With raw=True:
A     6
B    15
dtype: int64

## Specifies how the result will be returned

In [12]:
import pandas as pd

df = pd.DataFrame({'A': [1,9, 3], 'B': [4, 5, 6]})

def custom_function(x):
    return  x*2

result = df.apply(custom_function, axis=1, result_type='expand')
print(result)

    A   B
0   2   8
1  18  10
2   6  12

In [4]:
import pandas as pd

df = pd.DataFrame({'A': [1, 8, 3], 'B': [4, 5, 6]})

def custom_function(x):
    return [x*2]

result = df.apply(custom_function, axis=1, result_type='reduce')
print(result)

0      [[2, 8]]
1    [[16, 10]]
2     [[6, 12]]
dtype: object

In [81]:
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

def custom_function(x):
    return 100

result = df.apply(custom_function, axis=1, result_type='broadcast')
print(result)

     A    B
0  100  100
1  100  100
2  100  100

In [9]:
import pandas as pd

# Sample DataFrame
data = {'A': [1, 2, 3],
        'B': [4, 5, 6]}

df = pd.DataFrame(data)

# Define a function that returns a Series
def custom_function(row):
    return pd.Series([row['A'] * 2, row['B'] * 3], index=['A_double', 'B_triple'])
custom_function()
# Apply the function along the rows with result_type='expand'
#expanded_result = df.apply(custom_function, axis=1, result_type='expand')

#print(expanded_result)

TypeError: custom_function() missing 1 required positional argument: 'row'

In [10]:
import pandas as pd

# Sample DataFrame
data = {'A': [1, 2, 3],
        'B': [4, 5, 6]}

df = pd.DataFrame(data)

# Define a function that returns a Series
def custom_function(row):
    return pd.Series([row['A'] * 2, row['B'] * 3], index=['A_double', 'B_triple'])

# Create a sample row of data
sample_row = {'A': 4, 'B': 5}  # This is just an example, you can create any row you like

# Call custom_function with the sample row
result = custom_function(sample_row)
print(result)

A_double     8
B_triple    15
dtype: int64