### pandas.DataFrame.drop

### DataFrame.drop(labels=None, *, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')

1. Drop specified labels from rows or columns.
2. Remove rows or columns by specifying label names and corresponding axis, or by directly specifying index or column names. 
3. When using a multi-index, labels on different levels can be removed by specifying the level.

In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.arange(12).reshape(3, 4),
                  columns=['A', 'B', 'C', 'D'])
df

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [3]:
df.drop(['B', 'C'], axis=1)

   A   D
0  0   3
1  4   7
2  8  11

In [4]:
df.drop(columns=['B', 'C'])

   A   D
0  0   3
1  4   7
2  8  11

In [5]:
df.drop([0, 1])

   A  B   C   D
2  8  9  10  11

In [9]:
midx = pd.MultiIndex(levels=[['llama', 'cow', 'falcon'],
                             ['speed', 'weight', 'length']],
                     codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
                            [0, 1, 2, 0, 1, 2, 0, 1, 2]])
df = pd.DataFrame(index=midx, columns=['big', 'small'],
                  data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
                        [250, 150], [1.5, 0.8], [320, 250],
                        [1, 0.8], [0.3, 0.2]])
df

                 big  small
llama  speed    45.0   30.0
       weight  200.0  100.0
       length    1.5    1.0
cow    speed    30.0   20.0
       weight  250.0  150.0
       length    1.5    0.8
falcon speed   320.0  250.0
       weight    1.0    0.8
       length    0.3    0.2

In [7]:
df.drop(index=('falcon', 'weight'))

                 big  small
llama  speed    45.0   30.0
       weight  200.0  100.0
       length    1.5    1.0
cow    speed    30.0   20.0
       weight  250.0  150.0
       length    1.5    0.8
falcon speed   320.0  250.0
       length    0.3    0.2

In [8]:
df.drop(index='cow', columns='small')

                 big
llama  speed    45.0
       weight  200.0
       length    1.5
falcon speed   320.0
       weight    1.0
       length    0.3

In [10]:
df.drop(index='length', level=1)

                 big  small
llama  speed    45.0   30.0
       weight  200.0  100.0
cow    speed    30.0   20.0
       weight  250.0  150.0
falcon speed   320.0  250.0
       weight    1.0    0.8