# loc()

## Way to access and modify data based on labels (index and columns).

### Error : Raises KeyError if labels are not found in the index or columns.

In [108]:
import pandas as pd

In [109]:
data = {'A': [1, 2, 3, 4],
        'B': [5, 6, 7, 8],
        'C': [9, 10, 11, 12]}
df = pd.DataFrame(data)
df

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

## Getting Values

### Accessing a single element

In [110]:
print(df.loc[0, 'A'])

1

In [111]:
# data type of single element
print(type(df.loc[0, 'A']))

<class 'numpy.int64'>

### Accessing a single row

In [112]:
print(df.loc[2])

A     3
B     7
C    11
Name: 2, dtype: int64

In [113]:
# data type of single row
print(type(df.loc[2] ))

<class 'pandas.core.series.Series'>

### Accessing a single column

In [114]:
print(df.loc[:,'B'])

0    5
1    6
2    7
3    8
Name: B, dtype: int64

In [115]:
# data type of single column
print(type(df.loc[:,'B']))

<class 'pandas.core.series.Series'>

### Accessing multiple rows and columns

In [116]:
print(df.loc[0:2, 'A':'B'])

   A  B
0  1  5
1  2  6
2  3  7

In [117]:
### data type of multiple rows and columns
print(type(df.loc[0:2, 'A':'B']))

<class 'pandas.core.frame.DataFrame'>

### Accessing alternative rows and columns

In [118]:
print(df.loc[0:4:2])  # row-wise

   A  B   C
0  1  5   9
2  3  7  11

In [119]:
print(df.loc[:,'A':'C':2])  # Column-wise

   A   C
0  1   9
1  2  10
2  3  11
3  4  12

### Boolean list with the same length as the row axis

In [120]:
print(df.loc[[False, True, True, False]])

   A  B   C
1  2  6  10
2  3  7  11

In [121]:
# data type of boolean list
print(type(df.loc[[False, True, True, False]]))

<class 'pandas.core.frame.DataFrame'>

### Boolean list with the same length as the column axis

In [122]:
print(df.loc[:,[False, True, False]])

   B
0  5
1  6
2  7
3  8

In [123]:
# data types of boolean list
print(type(df.loc[:,[False, True, False]]))

<class 'pandas.core.frame.DataFrame'>

### Conditional that returns a boolean Series

In [124]:
print(df.loc[df['B'] > 6])

   A  B   C
2  3  7  11
3  4  8  12

In [125]:
# data type of conditional list
print(type(df.loc[df['B']>6]))  
# '  df['B']>6  ' data type is series as it returns in boolean and it is a one-dimensional object holding boolean values.
# '  df.loc[df['B']>6]  ' data type is DataFrame as it is a subset of the original DataFrame.

<class 'pandas.core.frame.DataFrame'>

### Condition with column labels specified

In [126]:
print(df.loc[df['B'] > 6, ['A']])

   A
2  3
3  4

In [127]:
# data type of conditional boolean series
print(type(df.loc[df['B'] > 6, ['A']]))

<class 'pandas.core.frame.DataFrame'>

### Multiple condition

#### Using &

In [128]:
print(df.loc[(df['A'] > 1) & (df['B'] < 8)])

   A  B   C
1  2  6  10
2  3  7  11

In [129]:
# data type of Multiple condition
print(type(df.loc[(df['A'] > 1) & (df['B'] < 8)]))

<class 'pandas.core.frame.DataFrame'>

#### Using |

In [130]:
print(df.loc[(df['A'] > 1) | (df['B'] < 8)])

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

### Callable that returns a boolean Series

In [131]:
df.loc[lambda df: df['C'] == 10]

   A  B   C
1  2  6  10

In [132]:
# data type of Callable function
print(type(df.loc[lambda df: df['C'] == 10]))

<class 'pandas.core.frame.DataFrame'>

## Setting values

### Set value for all items matching the list of labels

In [133]:
df.loc[[2,3],['B']] = 100
print(df)

   A    B   C
0  1    5   9
1  2    6  10
2  3  100  11
3  4  100  12

In [134]:
# data type of set value
print(type(df))

<class 'pandas.core.frame.DataFrame'>

### Set value for an entire row

In [135]:
df.loc[0] = 50
print(df)

    A    B   C
0  50   50  50
1   2    6  10
2   3  100  11
3   4  100  12

### Set value for an entire column

In [136]:
df.loc[:, 'C'] = 25
print(df)

    A    B   C
0  50   50  25
1   2    6  25
2   3  100  25
3   4  100  25

### Set value for rows matching callable condition

In [137]:
df.loc[df['B'] > 35] = 0
print(df)

   A  B   C
0  0  0   0
1  2  6  25
2  0  0   0
3  0  0   0

### Add value matching location

In [138]:
df.loc[2, "B"] += 10
print(df)

   A   B   C
0  0   0   0
1  2   6  25
2  0  10   0
3  0   0   0