### pandas.DataFrame.droplevel

### DataFrame.droplevel(level, axis=0)

### Return Series/DataFrame with requested index / column level(s) removed.

In [4]:
import pandas as pd
import numpy as np

df = pd.DataFrame([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]).set_index([0, 1]).rename_axis(['a', 'b'])
df

       2   3
a b
1 2    3   4
5 6    7   8
9 10  11  12

In [6]:
df.columns = pd.MultiIndex.from_tuples([
    ('c', 'e'), ('d', 'f')
], names=['level_1', 'level_2'])
df

level_1   c   d
level_2   e   f
a b
1 2       3   4
5 6       7   8
9 10     11  12

In [7]:
df.droplevel('a')

level_1   c   d
level_2   e   f
b
2         3   4
6         7   8
10       11  12

In [8]:
df.droplevel('level_2', axis=1)

level_1   c   d
a b
1 2       3   4
5 6       7   8
9 10     11  12